// seed-200.ts — run with:  npx tsx seed-200.ts
//
// Creates 15 NEW test student users (no collision with the original 5) and 200
// NEW listings across every ListingType. Every title and description is written
// by hand so the text is varied enough for semantic embeddings — no templating,
// no cross-joining of arrays. Runs directly against the DB via Prisma.
//
// Photos use picsum.photos placeholder URLs (real images, no upload needed).

import * as bcrypt from "bcryptjs";
import "dotenv/config";
import { prisma } from "./src/graphql/context";

// small helper for a placeholder image URL (varied per seed value)
const pic = (seed: string) => `https://picsum.photos/seed/${seed}/600/400`;

async function main() {
    console.log("Seeding (200): creating test users...");

    const passwordHash = await bcrypt.hash("Test1234!", 12);

    // ── 15 NEW test student users (fresh names / emails / edu_emails) ─────
    const usersData = [
        { name: "Burak",  surname: "Aydın",   username: "burak_test",  email: "burak@test.dev",  edu_email: "burak@ogr.deu.edu.tr",         university: "Dokuz Eylül Üniversitesi" },
        { name: "Selin",  surname: "Arslan",  username: "selin_test",  email: "selin@test.dev",  edu_email: "selin@ogr.ege.edu.tr",         university: "Ege Üniversitesi" },
        { name: "Can",    surname: "Öztürk",  username: "can_test",    email: "can@test.dev",    edu_email: "can@std.iyte.edu.tr",          university: "İYTE" },
        { name: "Deniz",  surname: "Koç",     username: "deniz_test",  email: "deniz@test.dev",  edu_email: "deniz@ogr.ikc.edu.tr",         university: "İzmir Katip Çelebi Üniversitesi" },
        { name: "Merve",  surname: "Yıldız",  username: "merve_test",  email: "merve@test.dev",  edu_email: "merve@std.izmirekonomi.edu.tr", university: "İzmir Ekonomi Üniversitesi" },
        { name: "Ozan",   surname: "Kurt",    username: "ozan_test",   email: "ozan@test.dev",   edu_email: "ozan@ogr.deu.edu.tr",          university: "Dokuz Eylül Üniversitesi" },
        { name: "Ece",    surname: "Aksoy",   username: "ece_test",    email: "ece@test.dev",    edu_email: "ece@ogr.ege.edu.tr",           university: "Ege Üniversitesi" },
        { name: "Kerem",  surname: "Doğan",   username: "kerem_test",  email: "kerem@test.dev",  edu_email: "kerem@std.yasar.edu.tr",       university: "Yaşar Üniversitesi" },
        { name: "Buse",   surname: "Erdoğan", username: "buse_test",   email: "buse@test.dev",   edu_email: "buse@ogr.bakircay.edu.tr",     university: "İzmir Bakırçay Üniversitesi" },
        { name: "Tolga",  surname: "Şimşek",  username: "tolga_test",  email: "tolga@test.dev",  edu_email: "tolga@std.iyte.edu.tr",        university: "İYTE" },
        { name: "Nazlı",  surname: "Polat",   username: "nazli_test",  email: "nazli@test.dev",  edu_email: "nazli@ogr.deu.edu.tr",         university: "Dokuz Eylül Üniversitesi" },
        { name: "Cenk",   surname: "Aslan",   username: "cenk_test",   email: "cenk@test.dev",   edu_email: "cenk@ogr.ege.edu.tr",          university: "Ege Üniversitesi" },
        { name: "İrem",   surname: "Güneş",   username: "irem_test",   email: "irem@test.dev",   edu_email: "irem@std.izmirekonomi.edu.tr", university: "İzmir Ekonomi Üniversitesi" },
        { name: "Barış",  surname: "Yavuz",   username: "baris_test",  email: "baris@test.dev",  edu_email: "baris@ogr.ikc.edu.tr",         university: "İzmir Katip Çelebi Üniversitesi" },
        { name: "Gizem",  surname: "Kılıç",   username: "gizem_test",  email: "gizem@test.dev",  edu_email: "gizem@std.yasar.edu.tr",       university: "Yaşar Üniversitesi" },
    ];

    const users = [];
    for (const u of usersData) {
        const user = await prisma.user.upsert({
            where: { email: u.email },
            update: {},
            create: {
                ...u,
                password: passwordHash,
                account_type: "student",
                auth_provider: "local",
                is_complete: true,
                is_verified: true,
            },
        });
        users.push(user);
    }
    console.log(`Created/verified ${users.length} users.`);

    // round-robin owner assignment so listings are spread across users
    let ownerIdx = 0;
    const nextOwner = () => users[ownerIdx++ % users.length].id;

    const oneMonthLater = () => {
        const d = new Date();
        d.setMonth(d.getMonth() + 1);
        return d;
    };
    const inDays = (n: number) => {
        const d = new Date();
        d.setDate(d.getDate() + n);
        return d;
    };
    const inHours = (n: number) => {
        const d = new Date();
        d.setHours(d.getHours() + n);
        return d;
    };

    // ── 200 listings — each written by hand, unique title + description ───
    const listings: any[] = [
        // ══════════════ SECONDHAND · electronics (18) ══════════════
        { title: "RTX 4060 8GB Ekran Kartı", description: "Geçen yıl kendim taktım, tek sahibiyim. Fatura ve kutu bende duruyor, garanti Ocak'a kadar geçerli. 1080p'de her oyunu rahat çeviriyor, hiç overclock yapmadım.", price: 11500, type: "secondhand", category: "electronics", condition: "like_new", location: "Bornova, İzmir", features: { "Bellek": "8GB GDDR6", "Marka": "MSI Ventus", "Garanti": "Devam ediyor", "Kutu": "Var" }, photos: [pic("rtx4060-a"), pic("rtx4060-b")] },
        { title: "iPhone 12 128GB Mavi", description: "Batarya sağlığı %86, ekranı çizik yok çünkü ilk günden beri koruyucu camla kullandım. Kılıf ve orijinal kablo veriyorum, adaptör yok. Face ID sorunsuz çalışıyor.", price: 15000, type: "secondhand", category: "electronics", condition: "good", location: "Alsancak, İzmir", features: { "Hafıza": "128GB", "Batarya": "%86", "Renk": "Mavi", "Aksesuar": "Kılıf + kablo" }, photos: [pic("ip12-1")] },
        { title: "iPad 9. Nesil 64GB", description: "Not tutmak için almıştım ama tablete pek ısınamadım. Apple Pencil uyumlu, kalem ayrı satılık. Ekranda tek bir iz bile yok.", price: 8900, type: "secondhand", category: "electronics", condition: "like_new", location: "Karşıyaka, İzmir", features: { "Hafıza": "64GB", "Nesil": "9. nesil", "Kalem uyumu": "Apple Pencil 1" }, photos: [pic("ipad9-x"), pic("ipad9-y")] },
        { title: "Sony WH-1000XM4 Kulaklık", description: "Kütüphanede çalışırken gürültü engelleme cankurtaran oluyordu ama daha küçük bir modele geçtim. Yastıkçıkları yeni, ter falan yok. Taşıma çantası ve kablosu dahil.", price: 4800, type: "secondhand", category: "electronics", condition: "good", location: "Konak, İzmir", features: { "Tip": "Kulak üstü", "ANC": "Var", "Bağlantı": "Bluetooth", "Çanta": "Dahil" }, photos: [pic("xm4-a")] },
        { title: "Harici SSD 500GB Type-C", description: "Video projelerimi taşımak için kullanıyordum, çok hızlı. Okuma yazma değerleri hâlâ ilk günkü gibi. Kablosu kutusunda geliyor.", price: 900, type: "secondhand", category: "electronics", condition: "like_new", location: "Buca, İzmir", features: { "Kapasite": "500GB", "Arayüz": "USB-C 3.2", "Marka": "SanDisk" }, photos: [pic("extssd-500")] },
        { title: "Logitech C920 Webcam", description: "Online derslerde ve sunumlarda kullandım, görüntüsü net. Artık dersler yüz yüze olduğu için ihtiyacım kalmadı. Klipsi sağlam, masaüstü monitöre rahat takılıyor.", price: 650, type: "secondhand", category: "electronics", condition: "good", location: "Kampüs", features: { "Çözünürlük": "1080p", "Mikrofon": "Dahili", "Bağlantı": "USB" }, photos: [pic("c920-cam")] },
        { title: "JBL Charge 4 Hoparlör", description: "Deniz kenarı ve yurt partileri için harikaydı, sesi gerçekten yüksek. Powerbank özelliğiyle telefon da şarj ediyor. Küçük bir kullanım izi dışında tertemiz.", price: 2100, type: "secondhand", category: "electronics", condition: "good", location: "Gaziemir, İzmir", features: { "Su geçirmez": "IPX7", "Batarya": "20 saat", "Powerbank": "Var" }, photos: [pic("jbl-charge")] },
        { title: "Logitech G502 Hero Mouse", description: "Oyun için aldığım ama tuş sayısı bana fazla geldi. Sensörü çok isabetli, sürüklenme yok. Ağırlık parçaları da kutusunda duruyor.", price: 700, type: "secondhand", category: "electronics", condition: "good", location: "Bornova, İzmir", features: { "Sensör": "25K DPI", "Tuş": "11 programlanabilir", "Ağırlık": "Ayarlanabilir" }, photos: [pic("g502-m")] },
        { title: "20000mAh Powerbank", description: "Kamp ve uzun otobüs yolculuklarında beni hiç yarı yolda bırakmadı. İki cihazı aynı anda şarj edebiliyor. Hızlı şarj destekliyor, kablosuyla veriyorum.", price: 550, type: "secondhand", category: "electronics", condition: "good", location: "Çiğli, İzmir", features: { "Kapasite": "20000mAh", "Çıkış": "2 USB + Type-C", "Hızlı şarj": "PD 20W" }, photos: [pic("pb-20k")] },
        { title: "TP-Link Archer C6 Router", description: "Ev taşıdım, yeni evde modem hediye geldi bu yüzden satıyorum. Dört antenli, kapsama alanı geniş. Sıfırlanmış halde teslim edebilirim.", price: 480, type: "secondhand", category: "electronics", condition: "good", location: "Bayraklı, İzmir", features: { "Bant": "Dual Band", "Hız": "AC1200", "Anten": "4 adet" }, photos: [pic("router-c6")] },
        { title: "Samsung Galaxy Tab A8", description: "Ders kitaplarını PDF okumak için çok işime yaradı, ekranı büyük ve gözü yormuyor. Kılıfıyla birlikte veriyorum. Şarjı bir günü rahat çıkarıyor.", price: 5200, type: "secondhand", category: "electronics", condition: "good", location: "Narlıdere, İzmir", features: { "Ekran": "10.5 inç", "Hafıza": "64GB", "Kılıf": "Dahil" }, photos: [pic("taba8")] },
        { title: "Xiaomi Mi Band 8 Akıllı Bileklik", description: "Koşularımı takip etmek için almıştım, uyku ölçümü de gayet iyi. Kordonu yeni değiştirdim. Kutusu ve şarj başlığı tam.", price: 700, type: "secondhand", category: "electronics", condition: "like_new", location: "Konak, İzmir", features: { "Ekran": "AMOLED", "Su geçirmez": "5ATM", "Batarya": "14 gün" }, photos: [pic("miband8")] },
        { title: "Dizüstü Soğutucu Stand", description: "Yaz aylarında laptopum çok ısınıyordu, bu tabla sıcaklığı belirgin düşürdü. Beş fanlı ve yükseklik ayarı var. Sessiz modda neredeyse hiç ses çıkarmıyor.", price: 350, type: "secondhand", category: "electronics", condition: "good", location: "Buca, İzmir", features: { "Fan": "5 adet", "Yükseklik": "Ayarlanabilir", "Bağlantı": "USB" }, photos: [pic("cooler-stand")] },
        { title: "USB Kondenser Mikrofon", description: "Podcast denemeleri için almıştım, sesi oldukça temiz kaydediyor. Masa ayağı ve pop filtresiyle geliyor. Kur da yok, tak çalıştır.", price: 1200, type: "secondhand", category: "electronics", condition: "like_new", location: "Alsancak, İzmir", features: { "Tip": "Kondenser", "Bağlantı": "USB", "Aksesuar": "Ayak + pop filtre" }, photos: [pic("usb-mic")] },
        { title: "Wacom Intuos Grafik Tablet", description: "Dijital çizime başlamak isteyen biri için ideal boyutta. Kalem basınç seviyesi bol, çizim çok akıcı. Kalem ucu yedekleri kutuda mevcut.", price: 1600, type: "secondhand", category: "electronics", condition: "good", location: "Kampüs", features: { "Boyut": "Small", "Basınç": "4096 seviye", "Bağlantı": "USB" }, photos: [pic("wacom-intuos")] },
        { title: "Masaüstü Kasa i5 8. Nesil", description: "Ödev ve ofis işleri için gayet yeterli, bende ikinci makineydi. GTX 1050 Ti takılı, çoğu oyunu orta ayarda açıyor. Monitör dahil değil, sadece kasa.", price: 9500, type: "secondhand", category: "electronics", condition: "fair", location: "Bornova, İzmir", features: { "İşlemci": "i5-8400", "RAM": "16GB", "Ekran kartı": "GTX 1050 Ti", "Depolama": "256GB SSD + 1TB HDD" }, photos: [pic("pc-i5-a"), pic("pc-i5-b")] },
        { title: "GTX 1660 Super Ekran Kartı", description: "Yeni sisteme geçtiğim için çıkardım, sorunsuz çalışıyor. 1080p oyunlarda hâlâ çok iş görür. Fanları temizledim, sessiz döner.", price: 4200, type: "secondhand", category: "electronics", condition: "good", location: "Karşıyaka, İzmir", features: { "Bellek": "6GB GDDR6", "Marka": "Gigabyte", "Fan": "2 adet" }, photos: [pic("gtx1660s")] },
        { title: "HyperX Cloud II Kablolu Kulaklık", description: "Uzun oyun seanslarında kulağı yormuyor, mikrofonu çıkarılabilir. Ses yalıtımı iyi, arkadaşlar net duyuyor. Ekstra kadife yastıkçıklar da veriliyor.", price: 950, type: "secondhand", category: "electronics", condition: "good", location: "Gaziemir, İzmir", features: { "Tip": "Kulak üstü", "Mikrofon": "Çıkarılabilir", "Bağlantı": "3.5mm + USB" }, photos: [pic("cloud2")] },

        // ══════════════ SECONDHAND · textbooks_and_notes (14) ══════════════
        { title: "Organik Kimya - McMurry", description: "Kimya bölümü ikinci sınıf dersinde okuttular, çok kapsamlı bir kaynak. İçinde önemli yerleri fosforlu kalemle işaretledim, hepsi okunaklı. Kapağı biraz yıpranmış ama sayfalar sağlam.", price: 320, type: "secondhand", category: "textbooks_and_notes", condition: "good", location: "Kampüs", features: { "Yazar": "McMurry", "Dil": "Türkçe", "Baskı": "9. baskı" }, photos: [pic("mcmurry")] },
        { title: "Devre Teorisi Sadiku", description: "Elektrik-elektronik bölümü için temel kaynak. Çözümlü örnekleri gerçekten sınavda işe yarıyor. İçi tertemiz, sadece birkaç sayfada kurşun kalem notu var.", price: 280, type: "secondhand", category: "textbooks_and_notes", condition: "good", location: "Bornova, İzmir", features: { "Yazar": "Sadiku", "Konu": "Devre analizi" }, photos: [pic("sadiku")] },
        { title: "Lineer Cebir Kitabı", description: "Matematik ve mühendislik ortak dersi için aldım, bol örnekli. Ekinde çözümlü test bölümü var. Hiç yazı yazmadım, sıfır gibi duruyor.", price: 200, type: "secondhand", category: "textbooks_and_notes", condition: "like_new", location: "Buca, İzmir", features: { "Konu": "Lineer cebir", "Ek": "Çözümlü sorular" }, photos: [pic("lineer-cebir")] },
        { title: "Netter Anatomi Atlası", description: "Tıp fakültesi birinci sınıfın olmazsa olmazı. Renkli çizimleri çok net, sınav öncesi hayat kurtarıyor. Bir arkadaşımdan almıştım, ben de mezun oldum artık.", price: 900, type: "secondhand", category: "textbooks_and_notes", condition: "good", location: "Balçova, İzmir", features: { "Yazar": "Netter", "Tür": "Atlas", "Renk": "Renkli baskı" }, photos: [pic("netter-a"), pic("netter-b")] },
        { title: "Makro İktisat Ders Kitabı", description: "İşletme ve iktisat bölümleri için standart kaynak, grafikleri açık anlatılmış. Konu sonu soruları vize hazırlığında çok yardımcı oldu. Kapak köşeleri hafif kıvrık.", price: 240, type: "secondhand", category: "textbooks_and_notes", condition: "good", location: "Alsancak, İzmir", features: { "Konu": "Makroekonomi", "Baskı": "Güncel" }, photos: [pic("makro-ikt")] },
        { title: "Head First Java", description: "Programlamaya yeni başlayanlar için harika bir kitap, görsel anlatımı çok akılda kalıcı. İngilizce ama dili gayet sade. Sayfaları temiz, sadece kapakta bir etiket izi var.", price: 350, type: "secondhand", category: "textbooks_and_notes", condition: "good", location: "Kampüs", features: { "Dil": "İngilizce", "Konu": "Java", "Seviye": "Başlangıç" }, photos: [pic("hf-java")] },
        { title: "Almanca A1-A2 Kitap Seti", description: "Erasmus'a hazırlanırken kullandığım set, ders ve çalışma kitabı birlikte. CD'si de kutuda duruyor. İçinde birkaç alıştırma kurşun kalemle yapılmış, silinebilir.", price: 300, type: "secondhand", category: "textbooks_and_notes", condition: "good", location: "Konak, İzmir", features: { "Seviye": "A1-A2", "İçerik": "Ders + çalışma kitabı", "CD": "Var" }, photos: [pic("almanca-set")] },
        { title: "Diferansiyel Denklemler El Notları", description: "Dönem boyunca tuttuğum düzenli notlar, hocanın vurguladığı bütün konular var. Çözülmüş örnek sorular ayrı bir deftere yazıldı, ikisini birlikte veriyorum. Yazım okunaklı, spiralli.", price: 120, type: "secondhand", category: "textbooks_and_notes", condition: "good", location: "Bornova, İzmir", features: { "Tip": "El yazısı not", "İçerik": "Konu + çözümlü örnek" }, photos: [pic("difdenk-not")] },
        { title: "Olasılık ve İstatistik Kaynağı", description: "İstatistik dersi için almıştım, formül özetleri arka kapakta toplu halde. Bol örnekli ve anlaşılır. Sayfaları yıpranmamış, temiz kullanıldı.", price: 220, type: "secondhand", category: "textbooks_and_notes", condition: "like_new", location: "Karşıyaka, İzmir", features: { "Konu": "Olasılık-istatistik", "Ek": "Formül özeti" }, photos: [pic("olasilik-kitap")] },
        { title: "Hukuka Giriş Kitabı", description: "Birinci sınıf temel hukuk dersinin ana kaynağı. Kavramları sade dille açıklıyor, ilk yıl için ideal. İçinde renkli ayraçlarla önemli maddeler işaretli.", price: 260, type: "secondhand", category: "textbooks_and_notes", condition: "good", location: "Gaziemir, İzmir", features: { "Konu": "Hukuka giriş", "Seviye": "1. sınıf" }, photos: [pic("hukuk-giris")] },
        { title: "Genel Biyoloji Campbell", description: "Biyoloji ve moleküler bölümler için dev bir kaynak, konu anlatımı çok detaylı. Ağır bir kitap ama içeriği o kadar dolu ki değiyor. Kapak sağlam, iç sayfalarda çizim yok.", price: 700, type: "secondhand", category: "textbooks_and_notes", condition: "good", location: "Buca, İzmir", features: { "Yazar": "Campbell", "Baskı": "Türkçe çeviri", "Sayfa": "1000+" }, photos: [pic("campbell-bio")] },
        { title: "TYT-AYT Tam Kaynak Seti", description: "Kardeşim üniversiteyi kazandı, elimizde bütün fasiküller kaldı. Matematik, fen ve Türkçe denemeleri dahil, çoğu hiç açılmadı. Küçük kardeşi olan biri için ekonomik çözüm.", price: 400, type: "secondhand", category: "textbooks_and_notes", condition: "like_new", location: "Çiğli, İzmir", features: { "İçerik": "TYT + AYT fasikül", "Ders": "Sayısal + sözel", "Durum": "Çoğu kullanılmamış" }, photos: [pic("tyt-ayt-set")] },
        { title: "Mimarlık Tarihi Kitabı", description: "Mimarlık bölümünün keyifli derslerinden birinin kaynağı, görselleri bol. Dönem projesi hazırlarken sık sık başvurdum. Büyük boy, kuşe kağıt, çok şık bir baskı.", price: 380, type: "secondhand", category: "textbooks_and_notes", condition: "good", location: "Alsancak, İzmir", features: { "Konu": "Mimarlık tarihi", "Kağıt": "Kuşe", "Görsel": "Bol" }, photos: [pic("mim-tarih")] },
        { title: "Mühendislik Ekonomisi Kitabı", description: "Endüstri mühendisliği dersinde okuttular, para akışı ve amortisman konuları net anlatılıyor. Örnek sorular sınav tarzına birebir uyuyor. Sadece ilk sayfada ismim yazılı, o da silinir.", price: 210, type: "secondhand", category: "textbooks_and_notes", condition: "good", location: "Kampüs", features: { "Konu": "Mühendislik ekonomisi", "Ek": "Örnek problemler" }, photos: [pic("muh-ekonomi")] },

        // ══════════════ SECONDHAND · dorm_and_housing (12) ══════════════
        { title: "Tekli Yatak ve Baza", description: "İki yıl kendi evimde kullandım, çok rahat bir yatak. Ortası çökmedi, leke yok çünkü hep alez kullandım. Sökülüp taşınabiliyor, nakliyede yardımcı olurum.", price: 2500, type: "secondhand", category: "dorm_and_housing", condition: "good", location: "Bornova, İzmir", features: { "Boyut": "90x190", "Tip": "Baza + yatak", "Alez": "Kullanıldı" }, photos: [pic("yatak-baza")] },
        { title: "Küçük Gardırop", description: "Öğrenci evim için almıştım, iki kapaklı ve içinde askılık var. Yer kaplamıyor, dar odalara uygun boyutta. Tek kişi kaldırabilir, montajı basit.", price: 1100, type: "secondhand", category: "dorm_and_housing", condition: "good", location: "Buca, İzmir", features: { "Kapı": "2 kapaklı", "Renk": "Beyaz", "Askılık": "Var" }, photos: [pic("gardirop-k")] },
        { title: "Elektrikli Battaniye", description: "İzmir kışları nem yüzünden üşütüyor, bu battaniye çok işime yaradı. Üç ısı kademesi var ve otomatik kapanıyor. Yıkanabilir, tertemiz teslim ederim.", price: 450, type: "secondhand", category: "dorm_and_housing", condition: "like_new", location: "Konak, İzmir", features: { "Kademe": "3 ısı seviyesi", "Yıkama": "Yıkanabilir", "Otomatik kapanma": "Var" }, photos: [pic("elk-battaniye")] },
        { title: "El Dokuması Kilim", description: "Odaya sıcak bir hava katıyor, deseni gerçekten hoş. Tüylenmiyor ve kolay temizleniyor. Taşınırken katlayıp veririm, hafif.", price: 600, type: "secondhand", category: "dorm_and_housing", condition: "good", location: "Karşıyaka, İzmir", features: { "Boyut": "120x180", "Tür": "Kilim", "Temizlik": "Kolay" }, photos: [pic("kilim-halı")] },
        { title: "Fon Perde Seti", description: "Evi boşaltıyorum, iki kanat fon perde ve tül birlikte. Rengi krem, her dekora uyar. Yıkandı, ütülü şekilde teslim ederim.", price: 300, type: "secondhand", category: "dorm_and_housing", condition: "good", location: "Gaziemir, İzmir", features: { "İçerik": "2 fon + tül", "Renk": "Krem", "Durum": "Yıkanmış" }, photos: [pic("perde-set")] },
        { title: "Üç Raflı Kitaplık", description: "Ders kitaplarım için almıştım, sağlam ve dengeli duruyor. Duvara sabitlemeye gerek kalmadı. Küçük bir çizik dışında sorunsuz.", price: 500, type: "secondhand", category: "dorm_and_housing", condition: "good", location: "Bornova, İzmir", features: { "Raf": "3 raf", "Malzeme": "Suntalam", "Renk": "Ceviz" }, photos: [pic("kitaplik-3")] },
        { title: "Katlanır Çamaşır Kurutmalık", description: "Balkonu olmayan öğrenci evi için birebir, açılıp kapanıyor. Paslanmaz, uzun süre kullandım hiç bozulmadı. Katlanınca dolap arkasına sığıyor.", price: 250, type: "secondhand", category: "dorm_and_housing", condition: "good", location: "Balçova, İzmir", features: { "Tip": "Katlanabilir", "Malzeme": "Paslanmaz", "Kapasite": "Geniş" }, photos: [pic("kurutmalik")] },
        { title: "Armut Koltuk (Puf)", description: "Oyun oynarken ya da film izlerken bayılıyordum ama taşınırken yer kalmadı. İçi dolgun, çökmedi. Kılıfı çıkıp yıkanabiliyor.", price: 400, type: "secondhand", category: "dorm_and_housing", condition: "good", location: "Alsancak, İzmir", features: { "Tip": "Armut koltuk", "Kılıf": "Yıkanabilir", "Renk": "Antrasit" }, photos: [pic("armut-puf")] },
        { title: "Komodin (Çekmeceli)", description: "Yatak yanına koymak için ideal, iki çekmecesi var. Sürgüleri sorunsuz açılıp kapanıyor. Üstünde küçük bir su izi var ama gözükmüyor.", price: 350, type: "secondhand", category: "dorm_and_housing", condition: "fair", location: "Çiğli, İzmir", features: { "Çekmece": "2 adet", "Renk": "Beyaz", "Malzeme": "MDF" }, photos: [pic("komodin")] },
        { title: "Kapaklı Ayakkabılık", description: "Antre için pratik bir çözüm, üç kat ayakkabı alıyor. Kapağı sayesinde toz almıyor. Montajlı halde teslim edebilirim.", price: 380, type: "secondhand", category: "dorm_and_housing", condition: "good", location: "Bayraklı, İzmir", features: { "Kapasite": "9 çift", "Kat": "3 kat", "Kapak": "Var" }, photos: [pic("ayakkabilik")] },
        { title: "Bez Portatif Dolap", description: "Kısa süreli kalacaklar için çok pratik, dakikalar içinde kuruluyor. Fermuarlı kapağı toz tutmuyor. Söküp poşetiyle veririm, taşıması çok kolay.", price: 220, type: "secondhand", category: "dorm_and_housing", condition: "good", location: "Buca, İzmir", features: { "Tip": "Bez dolap", "Kurulum": "Kolay", "Kapak": "Fermuarlı" }, photos: [pic("bez-dolap")] },
        { title: "Ofis Çalışma Sandalyesi", description: "Uzun ders çalışma seanslarında sırtımı yormadı, yüksekliği ayarlanıyor. Tekerlekleri sessiz, kolçakları sağlam. Sadece bir kolçakta ufak çizik var.", price: 750, type: "secondhand", category: "dorm_and_housing", condition: "good", location: "Kampüs", features: { "Tip": "Ofis sandalyesi", "Ayar": "Yükseklik ayarlı", "Tekerlek": "Var" }, photos: [pic("ofis-sandalye")] },

        // ══════════════ SECONDHAND · kitchenware (10) ══════════════
        { title: "Çift Katlı Tost Makinesi", description: "Sabah kahvaltıları için çok pratikti, dört dilim aynı anda oluyor. Yapışmaz yüzeyi hâlâ iyi durumda. İçini her kullanımdan sonra sildiğim için temiz.", price: 300, type: "secondhand", category: "kitchenware", condition: "good", location: "Bornova, İzmir", features: { "Kapasite": "4 dilim", "Yüzey": "Yapışmaz", "Güç": "1200W" }, photos: [pic("tost-mak")] },
        { title: "Filtre Kahve Makinesi", description: "Sınav dönemlerinin kahramanı, sabahları hızlıca demliyor. Cam sürahisi çatlaksız. Filtre kağıdı da birazını veriyorum yanında.", price: 400, type: "secondhand", category: "kitchenware", condition: "good", location: "Alsancak, İzmir", features: { "Kapasite": "1.2L", "Sürahi": "Cam", "Sıcak tutma": "Var" }, photos: [pic("filtre-kahve")] },
        { title: "Granit Tencere Seti", description: "Yedi parça komple set, ev taşırken fazla geldi. Yapışmaz tabanları hâlâ çok iyi, yemek dibe tutmuyor. Kapakları cam, tamamı sağlam.", price: 850, type: "secondhand", category: "kitchenware", condition: "good", location: "Karşıyaka, İzmir", features: { "Parça": "7 parça", "Yüzey": "Granit", "Kapak": "Cam" }, photos: [pic("tencere-set")] },
        { title: "Air Fryer 4L", description: "Yağsız pişirme için harika, patates ve tavuğu çıtır yapıyor. Sepeti bulaşık makinesinde yıkanabiliyor. Neredeyse hiç kullanmadım, yeni gibi.", price: 1100, type: "secondhand", category: "kitchenware", condition: "like_new", location: "Buca, İzmir", features: { "Kapasite": "4 litre", "Güç": "1400W", "Sepet": "Makinede yıkanır" }, photos: [pic("airfryer-4l")] },
        { title: "El Blenderı Seti", description: "Çorba ve smoothie için çok kullanışlı, doğrayıcı aparatı da geliyor. Motoru güçlü, buzu bile kırıyor. Aksesuarları eksiksiz teslim ederim.", price: 350, type: "secondhand", category: "kitchenware", condition: "good", location: "Konak, İzmir", features: { "Güç": "600W", "Aparat": "Doğrayıcı + çırpıcı", "Kademe": "Değişken hız" }, photos: [pic("el-blender")] },
        { title: "Elektrikli Çay Makinesi", description: "İki demlikli, sabah akşam çayımızı bununla demledik. Üst demlik cam, alt kısım paslanmaz. Kirecini yeni temizledim, tıkırında.", price: 450, type: "secondhand", category: "kitchenware", condition: "good", location: "Gaziemir, İzmir", features: { "Tip": "Çift demlik", "Üst demlik": "Cam", "Güç": "1800W" }, photos: [pic("cay-mak")] },
        { title: "24 Parça Yemek Takımı", description: "Altı kişilik tabak-bardak seti, öğrenci evi için tam ihtiyaç kadar. Hiç kırılan olmadı, hepsi tam. Porselen, mikrodalgada kullanılabilir.", price: 500, type: "secondhand", category: "kitchenware", condition: "good", location: "Balçova, İzmir", features: { "Kişilik": "6 kişilik", "Malzeme": "Porselen", "Parça": "24 parça" }, photos: [pic("yemek-takim")] },
        { title: "Bakır Cezve ve Fincan Takımı", description: "Türk kahvesi sevenler için şık bir set, altı fincan ve tabakları tam. Cezvesi geleneksel bakır, kalın taban. Hediye kutusuyla birlikte veriyorum.", price: 380, type: "secondhand", category: "kitchenware", condition: "like_new", location: "Alsancak, İzmir", features: { "Cezve": "Bakır", "Fincan": "6 adet", "Kutu": "Dahil" }, photos: [pic("cezve-fincan")] },
        { title: "Pirinç Pişirme Makinesi", description: "Yurtta yaşarken pilav ve bulguru dertsiz pişiriyordu, hiç dibi tutmadı. İçi ölçekli, su seviyesi belli. Buhar tepsisi de var, sebze de buğulanıyor.", price: 300, type: "secondhand", category: "kitchenware", condition: "good", location: "Çiğli, İzmir", features: { "Kapasite": "1.8L", "Buhar tepsisi": "Var", "İç kap": "Yapışmaz" }, photos: [pic("pirinc-pisirici")] },
        { title: "Granit Krep ve Omlet Tavası", description: "Sabah kahvaltılarının vazgeçilmezi, yumurta hiç yapışmıyor. Sapı ısınmıyor, tutması rahat. Az kullanıldı, çizik yok.", price: 200, type: "secondhand", category: "kitchenware", condition: "like_new", location: "Bornova, İzmir", features: { "Çap": "26 cm", "Yüzey": "Granit", "Sap": "Isınmaz" }, photos: [pic("granit-tava")] },

        // ══════════════ SECONDHAND · department_materials (10) ══════════════
        { title: "Diş Hekimliği Fantom Model Seti", description: "Preklinik derslerinde kullandığım alt-üst çene fantom seti. Dişler eksiksiz, kırık yok. Mezun oldum, ihtiyacı olan alt sınıflara ucuza bırakıyorum.", price: 1300, type: "secondhand", category: "department_materials", condition: "good", location: "Balçova, İzmir", features: { "İçerik": "Alt + üst çene", "Diş": "Eksiksiz", "Bölüm": "Diş hekimliği" }, photos: [pic("dis-fantom")] },
        { title: "Kimya Laboratuvar Önlüğü", description: "Beyaz pamuklu lab önlüğü, M beden. Birkaç kez giyildi, hiç kimyasal lekesi yok. Cepleri sağlam, düğmeleri tam.", price: 150, type: "secondhand", category: "department_materials", condition: "like_new", location: "Kampüs", features: { "Beden": "M", "Kumaş": "Pamuklu", "Renk": "Beyaz" }, photos: [pic("lab-onluk")] },
        { title: "Maket Bıçağı ve Kesim Seti", description: "Mimarlık maketleri için topladığım kesim takımı, farklı uçlar ve kesim matı dahil. Bıçaklar keskin, yedek bıçak paketi de veriyorum. Maket yapımına yeni başlayanlar için ideal.", price: 250, type: "secondhand", category: "department_materials", condition: "good", location: "Alsancak, İzmir", features: { "İçerik": "Maket bıçağı + mat", "Yedek uç": "Var", "Bölüm": "Mimarlık" }, photos: [pic("maket-set")] },
        { title: "Aneroid Tansiyon Aleti", description: "Hemşirelik uygulama dersleri için almıştım, ölçümü doğru. Manşonu temiz, stetoskoplu set. Çantasıyla birlikte veriyorum.", price: 350, type: "secondhand", category: "department_materials", condition: "good", location: "Buca, İzmir", features: { "Tip": "Aneroid", "Stetoskop": "Dahil", "Çanta": "Var" }, photos: [pic("tansiyon-aleti")] },
        { title: "Arduino ve Breadboard Deney Seti", description: "Elektronik derslerinde kullandığım komple set, kablolar, dirençler ve sensörler dahil. Arduino kartı sağlam çalışıyor. Kutulu şekilde düzenli teslim ederim.", price: 550, type: "secondhand", category: "department_materials", condition: "good", location: "Bornova, İzmir", features: { "İçerik": "Arduino + breadboard", "Ek": "Sensör + kablo seti", "Kutu": "Var" }, photos: [pic("arduino-set")] },
        { title: "Guaj Boya ve Fırça Seti", description: "Güzel sanatlar hazırlık döneminden kalan boyalar, renkler hâlâ canlı. Fırça takımı ve palet dahil. Birkaç tüp yarım ama çoğu neredeyse dolu.", price: 300, type: "secondhand", category: "department_materials", condition: "fair", location: "Konak, İzmir", features: { "Tür": "Guaj boya", "Ek": "Fırça + palet", "Renk": "12 renk" }, photos: [pic("guaj-boya")] },
        { title: "Dijital Multimetre", description: "Devre ölçümleri için güvenilir bir alet, direnç ve gerilim ölçümleri sapmasız. Probları sağlam. Pili yeni taktım.", price: 280, type: "secondhand", category: "department_materials", condition: "good", location: "Karşıyaka, İzmir", features: { "Tip": "Dijital", "Ölçüm": "V/A/Ω", "Prob": "Dahil" }, photos: [pic("multimetre")] },
        { title: "Lehim İstasyonu", description: "Ayarlanabilir sıcaklıklı lehim istasyonu, elektronik projeler için ideal. Ucu yeni, ısınması hızlı. Yanında lehim teli ve pasta veriyorum.", price: 650, type: "secondhand", category: "department_materials", condition: "good", location: "Gaziemir, İzmir", features: { "Sıcaklık": "Ayarlanabilir", "Güç": "60W", "Ek": "Lehim teli + pasta" }, photos: [pic("lehim-ist")] },
        { title: "Pantone Renk Kartelası", description: "Grafik tasarım öğrencileri için baskı öncesi renk seçiminde çok işe yarıyor. Sayfaları temiz, solma yok. Güncel serilerden, kapağı sağlam.", price: 700, type: "secondhand", category: "department_materials", condition: "good", location: "Kampüs", features: { "Tür": "Renk kartelası", "Seri": "Coated", "Bölüm": "Grafik tasarım" }, photos: [pic("pantone")] },
        { title: "Uzun Kollu Beyaz Laboratuvar Önlüğü", description: "Fen fakültesi laboratuvarları için, L beden. Yaka ve kol uçları temiz. İki cepli, yıkandı ve ütülendi.", price: 160, type: "secondhand", category: "department_materials", condition: "good", location: "Bornova, İzmir", features: { "Beden": "L", "Kol": "Uzun", "Cep": "2 cep" }, photos: [pic("beyaz-onluk")] },

        // ══════════════ SECONDHAND · transportation (9) ══════════════
        { title: "Dağ Bisikleti 27.5 Jant", description: "Kampüs ve şehir içi için sağlam bir bisiklet, 21 vitesli. Amortisörleri iyi, frenler yeni balata. Zincirini geçen ay yağladım, sürüşü çok akıcı.", price: 3800, type: "secondhand", category: "transportation", condition: "good", location: "Bornova, İzmir", features: { "Jant": "27.5", "Vites": "21 vites", "Fren": "V-fren", "Amortisör": "Ön" }, photos: [pic("dag-bisiklet-a"), pic("dag-bisiklet-b")] },
        { title: "Full Face Motosiklet Kaskı", description: "Motor kullanırken güvenle takmıştım, cam çizik değil. İç süngerleri çıkıp yıkanabiliyor, kokusuz. M beden, kafaya oturuşu güzel.", price: 900, type: "secondhand", category: "transportation", condition: "good", location: "Gaziemir, İzmir", features: { "Tip": "Full face", "Beden": "M", "Vizör": "Şeffaf" }, photos: [pic("kask-ff")] },
        { title: "Katlanır Bisiklet 20 Jant", description: "Toplu taşımaya bindirmek için ideal, saniyeler içinde katlanıyor. Bagaja rahat sığıyor. Şehir içi kısa mesafeler için biçilmiş kaftan.", price: 3200, type: "secondhand", category: "transportation", condition: "good", location: "Konak, İzmir", features: { "Jant": "20", "Katlanır": "Evet", "Vites": "6 vites" }, photos: [pic("katlanir-bisiklet")] },
        { title: "Bisiklet Işık ve Kilit Seti", description: "Ön beyaz arka kırmızı LED lamba, USB ile şarj oluyor. U kilit sağlam ve iki anahtarı da var. Gece sürüşleri için güvenli bir kombinasyon.", price: 300, type: "secondhand", category: "transportation", condition: "good", location: "Karşıyaka, İzmir", features: { "Işık": "Ön + arka LED", "Şarj": "USB", "Kilit": "U kilit" }, photos: [pic("bisiklet-isik-kilit")] },
        { title: "Ninebot Elektrikli Scooter", description: "İşe gidiş gelişte çok işime yaradı, tam şarjla 25 km rahat gidiyor. Lastikleri sağlam, fren hassas. Uygulamadan hız ve şarj takibi yapılabiliyor.", price: 6500, type: "secondhand", category: "transportation", condition: "good", location: "Bayraklı, İzmir", features: { "Menzil": "25 km", "Hız": "25 km/s", "Katlanır": "Evet", "Uygulama": "Var" }, photos: [pic("ninebot-scooter")] },
        { title: "Longboard Kaykay", description: "Kampüs içinde derse yetişmek için harika, tekerlekleri yumuşak zeminde sessiz. Rulmanları döndürdüm, kayışı çok akıcı. Alt tarafta doğal kullanım izleri var.", price: 800, type: "secondhand", category: "transportation", condition: "fair", location: "Alsancak, İzmir", features: { "Tip": "Longboard", "Tekerlek": "70mm", "Uzunluk": "100 cm" }, photos: [pic("longboard")] },
        { title: "Su Geçirmez Bisiklet Çantası", description: "Sele arkasına takılan, yağmurda içindekiler ıslanmıyor. Reflektörlü, gece görünürlüğü iyi. Fermuarları sağlam, hacmi geniş.", price: 250, type: "secondhand", category: "transportation", condition: "good", location: "Buca, İzmir", features: { "Su geçirmez": "Evet", "Montaj": "Sele arkası", "Reflektör": "Var" }, photos: [pic("bisiklet-canta")] },
        { title: "Araç İçi Manyetik Telefon Tutucu", description: "Navigasyon için pratik, mıknatısı güçlü telefonu düşürmüyor. Havalandırmaya takılıyor. Yanında kablosuz şarj pedi de var.", price: 180, type: "secondhand", category: "transportation", condition: "like_new", location: "Çiğli, İzmir", features: { "Montaj": "Havalandırma", "Tip": "Manyetik", "Ek": "Kablosuz şarj" }, photos: [pic("telefon-tutucu")] },
        { title: "Inline Paten (42 Numara)", description: "Kordon boyunca kaymak için almıştım, tekerlekleri hâlâ iyi durumda. Fren pabucu takılı, ayak bileğini iyi sarıyor. Koruma seti hediye.", price: 600, type: "secondhand", category: "transportation", condition: "good", location: "Narlıdere, İzmir", features: { "Numara": "42", "Tip": "Inline", "Ek": "Koruma seti" }, photos: [pic("inline-paten")] },

        // ══════════════ SECONDHAND · clothing (10) ══════════════
        { title: "Hakiki Deri Ceket (M)", description: "Klasik siyah biker model, deri yumuşak ve dökümlü. Birkaç sezon giydim ama çok bakımlıydı, çatlak yok. Astarı sağlam, fermuarlar akıcı.", price: 1400, type: "secondhand", category: "clothing", condition: "good", location: "Alsancak, İzmir", features: { "Beden": "M", "Malzeme": "Hakiki deri", "Renk": "Siyah" }, photos: [pic("deri-ceket")] },
        { title: "Oversize Kot Ceket", description: "Bol kesim, her kombine uyan bir mavi ton. Yıkamada rengi solmadı. Cepleri işlevsel, düğmeleri tam.", price: 400, type: "secondhand", category: "clothing", condition: "good", location: "Konak, İzmir", features: { "Beden": "L", "Kesim": "Oversize", "Renk": "Açık mavi" }, photos: [pic("kot-ceket")] },
        { title: "Nike Spor Ayakkabı (42)", description: "Günlük kullandığım koşu ayakkabısı, tabanı hâlâ yaylı. Dışı temiz, iç astar yıpranmamış. Birkaç kez giyildi diyebilirim, çok rahat.", price: 900, type: "secondhand", category: "clothing", condition: "good", location: "Bornova, İzmir", features: { "Numara": "42", "Marka": "Nike", "Tip": "Koşu" }, photos: [pic("nike-42")] },
        { title: "Kışlık Kadın Bot (38)", description: "İçi kürklü, İzmir kışında ayağı sıcak tutuyor. Tabanı kaymaz, yağmurda güvenli. Topuğu alçak, gün boyu rahat.", price: 450, type: "secondhand", category: "clothing", condition: "good", location: "Karşıyaka, İzmir", features: { "Numara": "38", "İç": "Kürklü", "Taban": "Kaymaz" }, photos: [pic("kadin-bot")] },
        { title: "Lacivert Takım Elbise (48)", description: "Mezuniyet töreni ve iş görüşmeleri için biçilmiş kaftan, sadece iki kez giyildi. Ceket ve pantolon birlikte, dar kesim. Kuru temizlemeden yeni çıktı.", price: 1200, type: "secondhand", category: "clothing", condition: "like_new", location: "Alsancak, İzmir", features: { "Beden": "48", "Kesim": "Slim fit", "Renk": "Lacivert" }, photos: [pic("takim-elbise")] },
        { title: "Oversize Kapüşonlu Sweatshirt", description: "Kalın ve yumuşak bir kumaş, sınav gecelerinin favorisiydi. Rengi solmadı, ipleri tam. Unisex kesim, herkese olur.", price: 250, type: "secondhand", category: "clothing", condition: "good", location: "Buca, İzmir", features: { "Beden": "L", "Kesim": "Oversize", "Renk": "Gri" }, photos: [pic("sweatshirt")] },
        { title: "Su Geçirmez Yağmurluk", description: "Kampüste ani sağanaklar için hayat kurtarıcı, katlanınca cebe sığıyor. Kapüşonu ayarlanabiliyor. Fermuarı su geçirmiyor.", price: 300, type: "secondhand", category: "clothing", condition: "like_new", location: "Gaziemir, İzmir", features: { "Su geçirmez": "Evet", "Katlanabilir": "Evet", "Kapüşon": "Ayarlı" }, photos: [pic("yagmurluk")] },
        { title: "Herschel Sırt Çantası", description: "Laptop bölmeli, günlük derslere fazlasıyla yetiyor. Fermuarları sağlam, hiç yırtık yok. İçi temiz, koku yok.", price: 550, type: "secondhand", category: "clothing", condition: "good", location: "Konak, İzmir", features: { "Marka": "Herschel", "Laptop bölmesi": "Var", "Hacim": "25L" }, photos: [pic("herschel-canta")] },
        { title: "Kadın Kaban (M)", description: "Uzun ve şık bir kaban, camel rengi her şeye uyuyor. Astarı sıcak tutuyor, düğmeleri tam. Bir kış giyildi, çok bakımlı.", price: 600, type: "secondhand", category: "clothing", condition: "good", location: "Balçova, İzmir", features: { "Beden": "M", "Renk": "Camel", "Boy": "Uzun" }, photos: [pic("kadin-kaban")] },
        { title: "Adidas Koşu Ayakkabısı (44)", description: "Sabah koşuları için almıştım, tabanı hafif ve esnek. Nefes alan kumaşı yazın terletmiyor. Dış görünüşü temiz, sadece taban altında doğal aşınma var.", price: 700, type: "secondhand", category: "clothing", condition: "good", location: "Bornova, İzmir", features: { "Numara": "44", "Marka": "Adidas", "Tip": "Koşu" }, photos: [pic("adidas-44")] },

        // ══════════════ SECONDHAND · hobbies_and_gaming (10) ══════════════
        { title: "Nintendo Switch OLED", description: "OLED ekranı gerçekten çok canlı, taşınabilir modda oynamak keyifli. Dock ve iki Joy-Con dahil. Ekran koruyucu ilk günden takılı, çizik yok.", price: 9500, type: "secondhand", category: "hobbies_and_gaming", condition: "like_new", location: "Alsancak, İzmir", features: { "Model": "OLED", "Joy-Con": "2 adet", "Dock": "Dahil", "Ekran koruyucu": "Var" }, photos: [pic("switch-oled-a"), pic("switch-oled-b")] },
        { title: "Xbox Series S 512GB", description: "Dijital konsol, kutusuyla birlikte veriyorum. Sessiz çalışıyor, ısınma problemi yok. Bir kol dahil, ekstra kol ayrıca satılık.", price: 8000, type: "secondhand", category: "hobbies_and_gaming", condition: "good", location: "Bornova, İzmir", features: { "Depolama": "512GB", "Kol": "1 adet", "Tip": "Dijital" }, photos: [pic("xbox-series-s")] },
        { title: "Ahşap Satranç Takımı", description: "El işçiliği taşlar, ağırlıklı ve dengeli duruyor. Tahtası katlanabilir, içine taşlar sığıyor. Turnuva boyu, oynaması keyifli.", price: 500, type: "secondhand", category: "hobbies_and_gaming", condition: "good", location: "Konak, İzmir", features: { "Malzeme": "Ahşap", "Boyut": "Turnuva", "Katlanır tahta": "Var" }, photos: [pic("satranc-ahsap")] },
        { title: "Elektro Gitar ve Amfi Seti", description: "Başlangıç için ideal bir paket, gitar akort tutuyor. Küçük amfi ile birlikte, kablo ve pena dahil. Manyetikleri temiz, cızırtı yok.", price: 3500, type: "secondhand", category: "hobbies_and_gaming", condition: "good", location: "Karşıyaka, İzmir", features: { "İçerik": "Gitar + amfi", "Ek": "Kablo + pena", "Seviye": "Başlangıç" }, photos: [pic("elektro-gitar")] },
        { title: "Canon EOS 200D DSLR", description: "Fotoğrafçılığa merak sardığım dönemde aldım, 18-55 lensiyle geliyor. Deklanşör sayısı düşük. Çanta, iki batarya ve hafıza kartı dahil.", price: 8500, type: "secondhand", category: "hobbies_and_gaming", condition: "good", location: "Buca, İzmir", features: { "Model": "EOS 200D", "Lens": "18-55mm", "Ek": "2 batarya + çanta + SD" }, photos: [pic("canon-200d-a"), pic("canon-200d-b")] },
        { title: "DJI Mini 2 Drone", description: "Gezi videoları için mükemmel, çok stabil uçuyor. Üç bataryalı fly more combo. Pervaneler yedekli, çantasıyla teslim.", price: 11000, type: "secondhand", category: "hobbies_and_gaming", condition: "like_new", location: "Gaziemir, İzmir", features: { "Model": "Mini 2", "Batarya": "3 adet", "Kamera": "4K", "Çanta": "Dahil" }, photos: [pic("dji-mini2")] },
        { title: "Lego Technic Set", description: "Toplama süreci çok keyifliydi, sonra sergiledim. Tüm parçalar tam, talimat kitapçığı var. Kutusu biraz eziktir ama parçalar kusursuz.", price: 1800, type: "secondhand", category: "hobbies_and_gaming", condition: "good", location: "Bornova, İzmir", features: { "Seri": "Technic", "Parça": "Tam", "Talimat": "Var" }, photos: [pic("lego-technic")] },
        { title: "İki Kişilik Kamp Çadırı", description: "Hafta sonu kamplarında kullandım, kurulumu çok kolay. Su almadı, tabanı sağlam. Şişme mat ile birlikte uygun fiyata bırakıyorum.", price: 900, type: "secondhand", category: "hobbies_and_gaming", condition: "good", location: "Narlıdere, İzmir", features: { "Kapasite": "2 kişi", "Su geçirmez": "Evet", "Ek": "Şişme mat" }, photos: [pic("kamp-cadir")] },
        { title: "Yoga Matı ve Ekipman Seti", description: "Evde çalışmak için topladığım set, mat kalın ve kaymıyor. Direnç bantları ve blok dahil. Hepsi temiz, taşıma askısıyla veriyorum.", price: 350, type: "secondhand", category: "hobbies_and_gaming", condition: "good", location: "Alsancak, İzmir", features: { "Mat kalınlığı": "8mm", "Ek": "Direnç bandı + blok", "Askı": "Var" }, photos: [pic("yoga-set")] },
        { title: "Pikap ve Plak Koleksiyonu", description: "Retro tarz bir pikap, dahili hoparlörü var ama hoparlöre de bağlanıyor. Yanında beş adet karışık tür plak veriyorum. İğnesi yeni, sesi net.", price: 2200, type: "secondhand", category: "hobbies_and_gaming", condition: "good", location: "Konak, İzmir", features: { "Tip": "Pikap", "Bağlantı": "Bluetooth + AUX", "Ek": "5 plak" }, photos: [pic("pikap-plak")] },

        // ══════════════ SECONDHAND · other (7) ══════════════
        { title: "Sukulent Saksı Seti", description: "Odaya yeşillik katmak isteyenler için beş farklı sukulent, hepsi sağlıklı. Seramik saksılar dekoratif. Bakımı çok kolay, çok su istemiyorlar.", price: 200, type: "secondhand", category: "other", condition: "good", location: "Karşıyaka, İzmir", features: { "Adet": "5 bitki", "Saksı": "Seramik", "Bakım": "Kolay" }, photos: [pic("sukulent-set")] },
        { title: "Orta Boy Valiz", description: "Erasmus ve tatil için birkaç kez kullandım, tekerlekleri sorunsuz dönüyor. Sert kabuk, içindekileri koruyor. Şifreli kilidi çalışıyor.", price: 700, type: "secondhand", category: "other", condition: "good", location: "Bornova, İzmir", features: { "Boyut": "Orta (24 inç)", "Kabuk": "Sert (ABS)", "Kilit": "Şifreli" }, photos: [pic("valiz-orta")] },
        { title: "Sessiz Duvar Saati", description: "Minimal tasarım, akrep-yelkovan sessiz çalışıyor gece rahatsız etmiyor. Pil dahil değil. Salona ya da odaya çok yakışıyor.", price: 150, type: "secondhand", category: "other", condition: "like_new", location: "Buca, İzmir", features: { "Tip": "Analog", "Mekanizma": "Sessiz", "Çap": "30 cm" }, photos: [pic("duvar-saati")] },
        { title: "Catan Kutu Oyunu", description: "Arkadaş buluşmalarının vazgeçilmeziydi, tüm parçaları tam. Kartlar yıpranmamış, kutusu sağlam. Türkçe kural kitapçığı içinde.", price: 500, type: "secondhand", category: "other", condition: "good", location: "Alsancak, İzmir", features: { "Oyuncu": "3-4 kişi", "Dil": "Türkçe", "Parça": "Tam" }, photos: [pic("catan")] },
        { title: "Çelik Termos ve Sefer Tası", description: "Kampüste yemek taşımak için pratik, sızdırmıyor. Termos sıcağı saatlerce tutuyor. İkisini birlikte veriyorum, tertemiz.", price: 250, type: "secondhand", category: "other", condition: "good", location: "Gaziemir, İzmir", features: { "Termos": "500ml çelik", "Sefer tası": "3 katlı", "Sızdırmazlık": "Var" }, photos: [pic("termos-sefer")] },
        { title: "Kırtasiye Toplu Paket", description: "Dönem başı için ideal, defterler, kalemler ve fosforlular karışık. Çoğu ambalajında hiç açılmamış. Tek tek almaktan çok daha uygun.", price: 180, type: "secondhand", category: "other", condition: "like_new", location: "Çiğli, İzmir", features: { "İçerik": "Defter + kalem + fosforlu", "Durum": "Çoğu paketli" }, photos: [pic("kirtasiye-paket")] },
        { title: "Otomatik Katlanır Şemsiye", description: "İzmir'in ani yağmurları için çantada durması gereken bir şemsiye. Tek tuşla açılıp kapanıyor, telleri sağlam. Rüzgarda ters dönmüyor.", price: 120, type: "secondhand", category: "other", condition: "good", location: "Konak, İzmir", features: { "Tip": "Otomatik", "Katlanır": "Evet", "Rüzgar dayanımı": "Var" }, photos: [pic("semsiye")] },

        // ══════════════ ROOMMATE (25) ══════════════
        { title: "Bornova'da 2+1'de Boş Oda", description: "Ege Üniversitesi'ne yürüme mesafesinde, ferah bir dairede oda arkadaşı arıyorum. Ev eşyalı ve aydınlık, mutfak ortak kullanım. Sakin, ders çalışmaya saygılı biriyle iyi anlaşırız.", price: 6500, type: "roommate", location: "Bornova, İzmir", smoking_allowed: "Hayır", pet_friendly: "Hayır", gender_preference: "Erkek", criteria: { "Bölüm": "Farketmez", "Yaşam düzeni": "Düzenli", "Aidat": "Kira dahil" }, photos: [pic("oda-bornova-1"), pic("oda-bornova-2")] },
        { title: "Buca'da Kız Öğrenciye Oda", description: "İki kişilik evde tek oda boşaldı, ev güneşli ve temiz. DEÜ kampüsüne dolmuşla on dakika. Ev işlerinde uyumlu, sorumluluk paylaşan biri olsun yeter.", price: 6000, type: "roommate", location: "Buca, İzmir", smoking_allowed: "Balkonda", pet_friendly: "Hayır", gender_preference: "Kadın", criteria: { "Cinsiyet": "Kadın", "Sigara": "Sadece balkon", "Temizlik": "Ortak" }, photos: [pic("oda-buca-1")] },
        { title: "Karşıyaka Deniz Manzaralı Oda", description: "Vapura yakın bir konumda, geniş balkonlu evimde oda arkadaşı arıyorum. Sabah kahvesini deniz manzarasına karşı içmek paha biçilmez. Evcil hayvanı olan biri de gelebilir, benim kedim var.", price: 7500, type: "roommate", location: "Karşıyaka, İzmir", smoking_allowed: "Hayır", pet_friendly: "Evet", gender_preference: "Farketmez", criteria: { "Evcil hayvan": "Kabul", "Manzara": "Deniz", "Ulaşım": "Vapura yakın" }, photos: [pic("oda-karsiyaka-1"), pic("oda-karsiyaka-2")] },
        { title: "Konak Merkezde Ekonomik Oda", description: "Şehrin tam kalbinde, her yere yürüme mesafesinde uygun fiyatlı bir oda. Ev biraz eski ama sıcak ve samimi. Gece geç saatlere kadar çalışan birine sorun olmaz.", price: 5500, type: "roommate", location: "Konak, İzmir", smoking_allowed: "Evet", pet_friendly: "Hayır", gender_preference: "Erkek", criteria: { "Konum": "Merkez", "Bütçe": "Ekonomik", "Sigara": "Serbest" }, photos: [pic("oda-konak-1")] },
        { title: "Alsancak'ta Sosyal Ev Arkadaşı", description: "Canlı bir mahallede, arkadaş ortamı seven biriyim ve benzer birini arıyorum. Ev toplantılarına, birlikte yemek yapmaya açığım. Kafeler ve barlar yürüme mesafesinde.", price: 8000, type: "roommate", location: "Alsancak, İzmir", smoking_allowed: "Balkonda", pet_friendly: "Evet", gender_preference: "Farketmez", criteria: { "Karakter": "Sosyal", "Ortak aktivite": "Var", "Konum": "Merkezi" }, photos: [pic("oda-alsancak-1")] },
        { title: "Gaziemir'de Sessiz Oda", description: "Havalimanına yakın sakin bir semtte, ders çalışmaya çok uygun bir oda. Ev yeni boyandı, eşyalar bakımlı. Sabah erken kalkan, gürültü yapmayan biriyle uyumlu olurum.", price: 6200, type: "roommate", location: "Gaziemir, İzmir", smoking_allowed: "Hayır", pet_friendly: "Hayır", gender_preference: "Kadın", criteria: { "Ortam": "Sessiz", "Yaşam düzeni": "Sabahçı", "Sigara": "İçilmez" }, photos: [pic("oda-gaziemir-1")] },
        { title: "İYTE Yakınında Oda (Urla Hattı)", description: "İYTE kampüsüne servisle rahat ulaşılan konumda oda boş. Ev geniş bahçeli, doğayla iç içe. Sakinliği seven, mühendislik öğrencisi tercihen anlaşabiliriz.", price: 5800, type: "roommate", location: "Gülbahçe, Urla", smoking_allowed: "Bahçede", pet_friendly: "Evet", gender_preference: "Erkek", criteria: { "Kampüs": "İYTE", "Ortam": "Bahçeli", "Bölüm": "Mühendislik tercih" }, photos: [pic("oda-urla-1")] },
        { title: "Balçova'da 3+1'de Oda", description: "Teleferik ve termal bölgeye yakın, üç odalı geniş evde oda arkadaşı arıyoruz. Ev halihazırda iki kişi, üçüncü kişiyi bekliyoruz. Ortak alanlar temiz tutulur, uyumlu bir düzenimiz var.", price: 6300, type: "roommate", location: "Balçova, İzmir", smoking_allowed: "Hayır", pet_friendly: "Hayır", gender_preference: "Erkek", criteria: { "Ev": "3+1", "Mevcut kişi": "2 kişi", "Düzen": "Uyumlu" }, photos: [pic("oda-balcova-1")] },
        { title: "Bayraklı'da Yeni Binada Oda", description: "Asansörlü, güvenlikli sitede modern bir dairede oda kiralıyorum. Isıtma merkezi, kışın çok rahat. Temizliğe önem veren, düzenli biriyle güzel bir ev hayatı olur.", price: 7000, type: "roommate", location: "Bayraklı, İzmir", smoking_allowed: "Hayır", pet_friendly: "Hayır", gender_preference: "Kadın", criteria: { "Bina": "Yeni + güvenlikli", "Isıtma": "Merkezi", "Temizlik": "Önemli" }, photos: [pic("oda-bayrakli-1")] },
        { title: "Narlıdere'de Denize Yakın Oda", description: "Sahile yürüme mesafesinde, sabah yürüyüşü sevenler için ideal konum. Ev ferah, oda eşyalı. Spor yapan, sağlıklı yaşamı benimseyen biriyle iyi anlaşırım.", price: 6800, type: "roommate", location: "Narlıdere, İzmir", smoking_allowed: "Hayır", pet_friendly: "Evet", gender_preference: "Farketmez", criteria: { "Konum": "Sahile yakın", "Yaşam tarzı": "Sporcu", "Oda": "Eşyalı" }, photos: [pic("oda-narlidere-1")] },
        { title: "Çiğli'de Öğrenciye Uygun Oda", description: "Katip Çelebi kampüsüne yakın, uygun fiyatlı bir oda. Toplu taşıma çok rahat, market ve eczane hemen yanda. Bütçesi kısıtlı öğrenciler için mantıklı bir seçenek.", price: 5200, type: "roommate", location: "Çiğli, İzmir", smoking_allowed: "Balkonda", pet_friendly: "Hayır", gender_preference: "Erkek", criteria: { "Kampüs": "İKÇÜ", "Bütçe": "Uygun", "Çevre": "Market yakın" }, photos: [pic("oda-cigli-1")] },
        { title: "Güzelbahçe'de Müstakil Evde Oda", description: "Bahçeli müstakil bir evde, huzurlu bir yaşam sunan oda. Şehrin gürültüsünden uzak, temiz hava. Araba sahibi biri için park sorunu yok, bahçede yer var.", price: 6000, type: "roommate", location: "Güzelbahçe, İzmir", smoking_allowed: "Bahçede", pet_friendly: "Evet", gender_preference: "Farketmez", criteria: { "Ev": "Müstakil bahçeli", "Park": "Var", "Ortam": "Huzurlu" }, photos: [pic("oda-guzelbahce-1")] },
        { title: "Bornova Ergene'de İki Kişilik", description: "Ergene mahallesinde, öğrenci yoğun bir bölgede oda arkadaşı arıyorum. Çevrede yemek ve kafe bol, sosyal hayat canlı. Ders çalışırken sessizliğe, hafta sonu eğlenceye açığım.", price: 6400, type: "roommate", location: "Bornova, İzmir", smoking_allowed: "Balkonda", pet_friendly: "Hayır", gender_preference: "Erkek", criteria: { "Bölge": "Öğrenci yoğun", "Sosyal": "Aktif", "Hafta içi": "Sessiz" }, photos: [pic("oda-ergene-1")] },
        { title: "Konak'ta Yüksek Lisans Öğrencisine", description: "Merkezi konumda, daha olgun bir ev düzeni arayan yüksek lisans öğrencisine oda. Ev sakin, gece hayatı beklemiyorum. Akademik çalışmaya odaklı biriyle rahat ederiz.", price: 7200, type: "roommate", location: "Konak, İzmir", smoking_allowed: "Hayır", pet_friendly: "Hayır", gender_preference: "Farketmez", criteria: { "Seviye": "Yüksek lisans", "Düzen": "Akademik", "Gürültü": "Az" }, photos: [pic("oda-konak-yl-1")] },
        { title: "Alsancak'ta Kısa Dönem Oda", description: "Bahar dönemi boyunca kalacak birine kısa süreli oda kiralıyorum. Erasmus ya da stajyer öğrenciler için uygun. Ev merkezi, ulaşım her yöne kolay.", price: 8500, type: "roommate", location: "Alsancak, İzmir", smoking_allowed: "Balkonda", pet_friendly: "Evet", gender_preference: "Farketmez", criteria: { "Süre": "Kısa dönem", "Hedef": "Erasmus/stajyer", "Ulaşım": "Kolay" }, photos: [pic("oda-alsancak-kisa-1")] },
        { title: "Buca Tınaztepe Kampüs Yanı", description: "DEÜ Tınaztepe kampüsünün hemen yanında, yürüyerek derse gidilecek konum. Ev sade ama sıcak, mutfak fonksiyonel. Sabah dersleri olan biri için ideal.", price: 6100, type: "roommate", location: "Buca, İzmir", smoking_allowed: "Hayır", pet_friendly: "Hayır", gender_preference: "Kadın", criteria: { "Kampüs": "Tınaztepe", "Mesafe": "Yürüme", "Sigara": "İçilmez" }, photos: [pic("oda-tinaztepe-1")] },
        { title: "Karşıyaka Bostanlı'da Ferah Oda", description: "Bostanlı sahiline yakın, geniş ve aydınlık bir oda. Akşam yürüyüşleri ve sahil kafeleri çok keyifli. Düzenli, iletişimi güçlü bir ev arkadaşı arıyorum.", price: 7300, type: "roommate", location: "Karşıyaka, İzmir", smoking_allowed: "Balkonda", pet_friendly: "Evet", gender_preference: "Kadın", criteria: { "Konum": "Bostanlı", "Oda": "Ferah", "İletişim": "İyi" }, photos: [pic("oda-bostanli-1")] },
        { title: "Gaziemir Sarnıç'ta Uygun Oda", description: "Sarnıç bölgesinde, İZBAN ile şehrin her yerine ulaşılabilen bir konum. Kira paylaşımı ekonomik, aidat düşük. Sade yaşayan, tasarruflu biriyle güzel geçinir.", price: 5000, type: "roommate", location: "Gaziemir, İzmir", smoking_allowed: "Evet", pet_friendly: "Hayır", gender_preference: "Erkek", criteria: { "Ulaşım": "İZBAN", "Bütçe": "Düşük", "Aidat": "Az" }, photos: [pic("oda-sarnic-1")] },
        { title: "Bornova Kazımdirik'te Oda", description: "Metro istasyonuna yakın, öğrenci dostu bir mahallede oda. Yemek yerleri ve kütüphane çevrede bol. Uyumlu bir ev düzeni kurabileceğim biriyle anlaşmak isterim.", price: 6600, type: "roommate", location: "Bornova, İzmir", smoking_allowed: "Balkonda", pet_friendly: "Hayır", gender_preference: "Farketmez", criteria: { "Ulaşım": "Metro yakın", "Çevre": "Öğrenci dostu", "Düzen": "Uyumlu" }, photos: [pic("oda-kazimdirik-1")] },
        { title: "Konak Göztepe'de Manzaralı Oda", description: "Yüksek katta, körfez manzarasına bakan bir oda. Akşamları gün batımı harika. Sessizliğe önem veren, kendi halinde biriyle rahat bir ev olur.", price: 7800, type: "roommate", location: "Konak, İzmir", smoking_allowed: "Hayır", pet_friendly: "Hayır", gender_preference: "Kadın", criteria: { "Kat": "Yüksek", "Manzara": "Körfez", "Karakter": "Sakin" }, photos: [pic("oda-goztepe-1")] },
        { title: "Çiğli Egekent'te İki Kişilik", description: "Egekent sitesinde, güvenlikli ve çocuklu ailelere uygun sakin bir çevrede oda. Ev geniş, ortak alanlar rahat. Düzenli yaşayan biriyle uzun süreli anlaşmak isterim.", price: 5600, type: "roommate", location: "Çiğli, İzmir", smoking_allowed: "Hayır", pet_friendly: "Hayır", gender_preference: "Erkek", criteria: { "Site": "Güvenlikli", "Süre": "Uzun dönem", "Çevre": "Sakin" }, photos: [pic("oda-egekent-1")] },
        { title: "Bayraklı Manavkuyu'da Yeni Oda", description: "Yeni yapılan bir sitede, modern ve ışıl ışıl bir oda. Isı yalıtımı iyi, faturalar düşük. Temizlik ve düzen konusunda hassas biriyle iyi anlaşırız.", price: 7100, type: "roommate", location: "Bayraklı, İzmir", smoking_allowed: "Hayır", pet_friendly: "Evet", gender_preference: "Farketmez", criteria: { "Bina": "Yeni", "Fatura": "Düşük", "Temizlik": "Hassas" }, photos: [pic("oda-manavkuyu-1")] },
        { title: "Buca Şirinyer'de Merkezi Oda", description: "Şirinyer metro ve pazarına yakın, ulaşımı çok pratik bir konum. Ev sade ve temiz, oda eşyalı. Sosyalleşmeye açık ama evde huzur isteyen biriyle uyumluyum.", price: 5900, type: "roommate", location: "Buca, İzmir", smoking_allowed: "Balkonda", pet_friendly: "Hayır", gender_preference: "Kadın", criteria: { "Ulaşım": "Metro yakın", "Oda": "Eşyalı", "Karakter": "Dengeli" }, photos: [pic("oda-sirinyer-1")] },
        { title: "Alsancak Kıbrıs Şehitleri'nde Oda", description: "En hareketli caddelerden birine yakın, şehir hayatının içinde bir oda. Gece geç dönenler için sorun olmaz, ben de öyleyim. Enerjik, dışa dönük bir ev arkadaşı arıyorum.", price: 8200, type: "roommate", location: "Alsancak, İzmir", smoking_allowed: "Evet", pet_friendly: "Evet", gender_preference: "Farketmez", criteria: { "Konum": "Cadde yakını", "Yaşam": "Hareketli", "Karakter": "Enerjik" }, photos: [pic("oda-kibrissehitleri-1")] },
        { title: "Narlıdere Sahilköy'de Huzurlu Oda", description: "Deniz kokusu gelen, sakin bir mahallede oda kiralıyorum. Sabahları koşuya çıkmak için harika bir çevre. İç huzuruna önem veren, sakin biriyle güzel bir ev kurarız.", price: 6700, type: "roommate", location: "Narlıdere, İzmir", smoking_allowed: "Hayır", pet_friendly: "Evet", gender_preference: "Kadın", criteria: { "Çevre": "Sahil", "Ortam": "Huzurlu", "Aktivite": "Koşu" }, photos: [pic("oda-sahilkoy-1")] },

        // ══════════════ CARPOOLING (20) ══════════════
        { title: "Bornova → Çeşme Hafta Sonu", description: "Cumartesi sabahı Çeşme'ye gidiyorum, dönüş pazar akşamı. Denize gidip kafasını dağıtmak isteyen üç kişiye yer var. Yakıt masrafını bölüşürüz, müzik zevkim iyidir.", price: 150, type: "carpooling", location: "Bornova, İzmir", origin: "Bornova, İzmir", destination: "Çeşme, İzmir", departure_date: inDays(4), available_seats: 3, photos: [pic("yol-cesme")] },
        { title: "İzmir → Ankara Cuma Akşamı", description: "Cuma akşamı işten sonra Ankara'ya yola çıkıyorum, sabah orada oluruz. Uzun yol olduğu için sohbet edecek yol arkadaşı iyi olur. Molalarda çay-kahve benden.", price: 350, type: "carpooling", location: "Konak, İzmir", origin: "Konak, İzmir", destination: "Ankara", departure_date: inDays(6), available_seats: 2, photos: [pic("yol-ankara")] },
        { title: "Buca → İYTE Sabah Servisi", description: "Hafta içi her sabah Buca'dan İYTE kampüsüne gidiyorum. Dokuz derslerine yetişecek şekilde erken çıkıyorum. Aynı yolda olan bir kişiyi düzenli alabilirim.", price: 40, type: "carpooling", location: "Buca, İzmir", origin: "Buca, İzmir", destination: "Gülbahçe, Urla", departure_date: inDays(1), available_seats: 1, criteria: { "Sıklık": "Her sabah", "Saat": "Erken" }, photos: [pic("yol-iyte-sabah")] },
        { title: "İzmir → İstanbul Bayram Dönüşü", description: "Bayram tatili sonrası İstanbul'a dönüyorum, konforlu bir araçla rahat bir yolculuk. Bagaj yeri geniş, valizler sığar. Sigara içmeyen üç yolcu alabilirim.", price: 400, type: "carpooling", location: "Bornova, İzmir", origin: "Bornova, İzmir", destination: "İstanbul", departure_date: inDays(9), available_seats: 3, criteria: { "Sigara": "İçilmez", "Bagaj": "Geniş" }, photos: [pic("yol-istanbul")] },
        { title: "Karşıyaka → Alaçatı Sabah", description: "Cumartesi sabahı Alaçatı'ya kahvaltıya gidiyoruz, akşam dönüş var. Taş sokaklarda gezmek isteyen iki kişiye yerimiz var. Keyifli bir gün olacak.", price: 130, type: "carpooling", location: "Karşıyaka, İzmir", origin: "Karşıyaka, İzmir", destination: "Alaçatı, Çeşme", departure_date: inDays(5), available_seats: 2, photos: [pic("yol-alacati")] },
        { title: "İzmir → Denizli Pamukkale Turu", description: "Hafta sonu Pamukkale'yi görmeye gidiyorum, gezmeyi seven arkadaşlar aranıyor. Sabah erken çıkıp akşam dönme planı. Yol boyunca müzik ve sohbet garantili.", price: 200, type: "carpooling", location: "Konak, İzmir", origin: "Konak, İzmir", destination: "Denizli", departure_date: inDays(7), available_seats: 3, photos: [pic("yol-pamukkale")] },
        { title: "Gaziemir → Kampüs Öğle Dönüşü", description: "Öğleden sonra dersim bitince Gaziemir'e dönüyorum, aynı yönde olan birini alabilirim. Genelde saat üç gibi çıkıyorum. Düzenli bir yolcu olursa çok iyi olur.", price: 35, type: "carpooling", location: "Gaziemir, İzmir", origin: "Kampüs", destination: "Gaziemir, İzmir", departure_date: inDays(1), available_seats: 1, photos: [pic("yol-gaziemir")] },
        { title: "İzmir → Bodrum Yaz Kaçamağı", description: "Cuma öğlen Bodrum'a iniyorum, birkaç gün kalıp döneceğim. Deniz ve eğlence isteyenler için ideal. Yol masrafını paylaşırız, aracım rahat.", price: 250, type: "carpooling", location: "Alsancak, İzmir", origin: "Alsancak, İzmir", destination: "Bodrum, Muğla", departure_date: inDays(3), available_seats: 2, photos: [pic("yol-bodrum")] },
        { title: "Bornova → Manisa Akşam", description: "Akşamları Manisa'ya dönen biriyim, hafta içi düzenli gidiş var. Kısa ve konforlu bir yol. Aynı hatta olan bir kişiyi rahatlıkla alabilirim.", price: 60, type: "carpooling", location: "Bornova, İzmir", origin: "Bornova, İzmir", destination: "Manisa", departure_date: inDays(2), available_seats: 1, criteria: { "Sıklık": "Hafta içi akşam" }, photos: [pic("yol-manisa")] },
        { title: "İzmir → Muğla Fethiye", description: "Uzun hafta sonu Fethiye'ye tatile gidiyorum, paylaşımlı yolculuk arıyorum. Manzarası güzel bir güzergah. İki kişilik yer var, keyifli bir yol olur.", price: 300, type: "carpooling", location: "Konak, İzmir", origin: "Konak, İzmir", destination: "Fethiye, Muğla", departure_date: inDays(8), available_seats: 2, photos: [pic("yol-fethiye")] },
        { title: "Buca → Karşıyaka Akşam Dönüşü", description: "Stajım Karşıyaka'da, akşam Buca'ya dönüyorum. Şehir içi trafiğinde tek başına gitmektense paylaşmak daha keyifli. Yakıt ve köprü ücretini bölüşürüz.", price: 45, type: "carpooling", location: "Buca, İzmir", origin: "Karşıyaka, İzmir", destination: "Buca, İzmir", departure_date: inDays(1), available_seats: 2, photos: [pic("yol-buca-karsiyaka")] },
        { title: "İzmir → Aydın Kuşadası", description: "Cumartesi Kuşadası'na deniz için gidiyorum, akşam geç dönüş. Sahilde gün geçirmek isteyen üç arkadaş alabilirim. Plaj çantalarınızı hazırlayın.", price: 120, type: "carpooling", location: "Gaziemir, İzmir", origin: "Gaziemir, İzmir", destination: "Kuşadası, Aydın", departure_date: inDays(5), available_seats: 3, photos: [pic("yol-kusadasi")] },
        { title: "Bornova → Foça Pazar Gezisi", description: "Pazar günü Foça'ya kahvaltı ve balık yemeye gidiyoruz. Sakin bir sahil kasabası, çok huzurlu. İki kişilik yerimiz var, dönüş akşamüstü.", price: 90, type: "carpooling", location: "Bornova, İzmir", origin: "Bornova, İzmir", destination: "Foça, İzmir", departure_date: inDays(6), available_seats: 2, photos: [pic("yol-foca")] },
        { title: "İzmir → Balıkesir Ayvalık", description: "Hafta sonu Ayvalık'a gidiyorum, zeytinlikler ve deniz için. Uzunca bir yol ama manzarası güzel. Sigara içmeyen iki yolcu tercih ederim.", price: 180, type: "carpooling", location: "Karşıyaka, İzmir", origin: "Karşıyaka, İzmir", destination: "Ayvalık, Balıkesir", departure_date: inDays(7), available_seats: 2, criteria: { "Sigara": "İçilmez" }, photos: [pic("yol-ayvalik")] },
        { title: "Konak → Kampüs Sabah", description: "Her sabah Konak'tan kampüse gidiyorum, ilk derslere yetişecek şekilde. Trafik yoğun olduğu için erken çıkmak şart. Aynı saatlerde giden bir kişiyi düzenli alabilirim.", price: 30, type: "carpooling", location: "Konak, İzmir", origin: "Konak, İzmir", destination: "Kampüs", departure_date: inDays(1), available_seats: 1, criteria: { "Saat": "08:00 civarı", "Sıklık": "Her gün" }, photos: [pic("yol-konak-kampus")] },
        { title: "İzmir → Uşak Aile Ziyareti", description: "Ay sonu Uşak'a ailemin yanına gidiyorum, dönüş birkaç gün sonra. Sakin bir sürücüyümdür, molalarda dinleniriz. Bir yolcu için yerim var.", price: 220, type: "carpooling", location: "Buca, İzmir", origin: "Buca, İzmir", destination: "Uşak", departure_date: inDays(12), available_seats: 1, photos: [pic("yol-usak")] },
        { title: "Alsancak → Çiğli Akşam Servisi", description: "Akşam işten Çiğli'ye dönerken aynı yönde olanları alabilirim. Trafikte sohbet daha keyifli oluyor. Düzenli bir yolcuysanız ideal olur.", price: 40, type: "carpooling", location: "Alsancak, İzmir", origin: "Alsancak, İzmir", destination: "Çiğli, İzmir", departure_date: inDays(2), available_seats: 2, photos: [pic("yol-cigli-aksam")] },
        { title: "İzmir → Antalya Uzun Yol", description: "Sömestr tatilinde Antalya'ya iniyorum, uzun ama keyifli bir yol. Nöbetleşe sürebilecek ehliyetli biri olursa çok iyi olur. Üç kişilik yer mevcut.", price: 450, type: "carpooling", location: "Bornova, İzmir", origin: "Bornova, İzmir", destination: "Antalya", departure_date: inDays(14), available_seats: 3, criteria: { "Ehliyet": "Tercih", "Yol": "Uzun" }, photos: [pic("yol-antalya")] },
        { title: "Gaziemir → Torbalı Hafta İçi", description: "Hafta içi her gün Torbalı'ya gidiş gelişim var, sabah erken akşam geç. Aynı hatta olan öğrenci ya da çalışanı düzenli alabilirim. Yol ücreti çok makul.", price: 50, type: "carpooling", location: "Gaziemir, İzmir", origin: "Gaziemir, İzmir", destination: "Torbalı, İzmir", departure_date: inDays(1), available_seats: 2, criteria: { "Sıklık": "Her gün" }, photos: [pic("yol-torbali")] },
        { title: "İzmir → Kütahya Bahar Şenliği", description: "Kütahya'daki üniversite şenliğine gidiyoruz, coşkulu bir hafta sonu olacak. Müzik ve konser için gidenlere katılın. İki kişilik boş yer var, dönüş pazar gecesi.", price: 240, type: "carpooling", location: "Konak, İzmir", origin: "Konak, İzmir", destination: "Kütahya", departure_date: inDays(10), available_seats: 2, photos: [pic("yol-kutahya")] },

        // ══════════════ COURSE (15) ══════════════
        { title: "Calculus 1 Özel Ders", description: "Matematik bölümü öğrencisiyim, limit-türev-integral konularında zorlanan arkadaşlara yardımcı oluyorum. Sınav öncesi yoğun program yapabiliriz. Anlatımım sabırlı ve örnek odaklı.", price: 300, type: "course", location: "Bornova, İzmir", subject: "Matematik", format: "in_person", criteria: { "Seviye": "1. sınıf", "Süre": "Ders başı 90 dk", "Yer": "Kütüphane/kafe" }, photos: [pic("ders-calculus")] },
        { title: "Python'a Sıfırdan Giriş", description: "Yazılıma hiç bulaşmamış biri için tasarladığım online ders serisi. Değişkenlerden başlayıp küçük projelere kadar ilerliyoruz. Her ders sonunda pratik ödev veriyorum.", price: 250, type: "course", location: "Online", subject: "Programlama", format: "online", criteria: { "Ön koşul": "Yok", "Araç": "Zoom + kod editörü", "Ödev": "Var" }, photos: [pic("ders-python")] },
        { title: "İngilizce Konuşma Pratiği", description: "IELTS'ten yüksek puan aldım, akıcı konuşmak isteyenlerle sohbet ağırlıklı dersler yapıyorum. Gramerden çok pratiğe odaklanıyoruz. Gerçek hayatta kullanacağın kalıpları öğreteceğim.", price: 200, type: "course", location: "Online", subject: "İngilizce", format: "online", criteria: { "Seviye": "B1 ve üzeri", "Odak": "Konuşma", "Sıklık": "Haftada 2" }, photos: [pic("ders-ingilizce")] },
        { title: "Fizik 1 Grup Dersi", description: "Mekanik ve Newton yasaları konusunda üç-dört kişilik gruplarla çalışıyorum. Grup olunca hem ekonomik hem de birbirinizden öğreniyorsunuz. Vize haftası ekstra seans açabilirim.", price: 150, type: "course", location: "Buca, İzmir", subject: "Fizik", format: "in_person", criteria: { "Grup": "3-4 kişi", "Konu": "Mekanik", "Yer": "Kampüs" }, photos: [pic("ders-fizik")] },
        { title: "AutoCAD ve Teknik Çizim", description: "Mimarlık ve mühendislik öğrencileri için AutoCAD'i uygulamalı öğretiyorum. Kendi projen üzerinden ilerlersek daha kalıcı oluyor. Ekran paylaşımıyla adım adım gösteriyorum.", price: 350, type: "course", location: "Online", subject: "CAD", format: "online", criteria: { "Program": "AutoCAD", "Yöntem": "Proje bazlı", "Bölüm": "Mimarlık/mühendislik" }, photos: [pic("ders-autocad")] },
        { title: "Organik Kimya Takviye", description: "Reaksiyon mekanizmaları gözünü korkutuyorsa doğru yerdesin, mantığını kavratmaya odaklanıyorum. Ezber yerine anlama üzerine kurulu bir yöntemim var. Bol soru çözerek pekiştiriyoruz.", price: 280, type: "course", location: "Bornova, İzmir", subject: "Kimya", format: "in_person", criteria: { "Konu": "Organik kimya", "Yöntem": "Mantık odaklı", "Materyal": "Soru bankası" }, photos: [pic("ders-organik")] },
        { title: "Almanca A1-A2 Ders", description: "Erasmus için Almanca öğrenmek isteyenlere temelden başlıyorum. Telaffuz ve günlük konuşmaya ağırlık veriyorum. Materyalleri ben sağlıyorum, ekstra kitap almana gerek yok.", price: 220, type: "course", location: "Online", subject: "Almanca", format: "online", criteria: { "Seviye": "A1-A2", "Materyal": "Dahil", "Odak": "Konuşma + telaffuz" }, photos: [pic("ders-almanca")] },
        { title: "İstatistik ve SPSS", description: "Tez ve proje için veri analizine ihtiyacı olan lisans-yüksek lisans öğrencilerine yardımcı oluyorum. SPSS'te hangi testi ne zaman kullanacağını öğreteceğim. Kendi verinle çalışabiliriz.", price: 400, type: "course", location: "Online", subject: "İstatistik", format: "online", criteria: { "Program": "SPSS", "Hedef": "Tez/proje", "Veri": "Kendi verin" }, photos: [pic("ders-spss")] },
        { title: "Gitar Başlangıç Dersleri", description: "Müzik okuyorum, sıfırdan gitara başlamak isteyenlere temel akorları ve ritmi öğretiyorum. İlk aydan sonra basit şarkılar çalabiliyorsun. Gitarını yanında getirmen yeterli.", price: 250, type: "course", location: "Karşıyaka, İzmir", subject: "Müzik", format: "in_person", criteria: { "Seviye": "Başlangıç", "Enstrüman": "Kendi gitarın", "Süre": "60 dk" }, photos: [pic("ders-gitar")] },
        { title: "Devre Analizi Sınav Hazırlık", description: "Elektrik-elektronik öğrencisi olarak devre çözümünü basit adımlara indiriyorum. Kirchhoff ve düğüm analizini kafana oturtacağız. Final öncesi yoğunlaştırılmış program mevcut.", price: 300, type: "course", location: "Bornova, İzmir", subject: "Elektrik", format: "in_person", criteria: { "Konu": "Devre analizi", "Program": "Final yoğun", "Yer": "Kampüs" }, photos: [pic("ders-devre")] },
        { title: "Adobe Photoshop Temelleri", description: "Grafik tasarıma ilgi duyanlar için Photoshop'un temellerini eğlenceli şekilde öğretiyorum. Katmanlar, maskeler ve renk düzenlemeyi uygulamalı geçiyoruz. Kendi tasarımını yaparak bitiriyorsun.", price: 320, type: "course", location: "Online", subject: "Grafik Tasarım", format: "online", criteria: { "Program": "Photoshop", "Seviye": "Başlangıç", "Çıktı": "Kendi tasarımın" }, photos: [pic("ders-photoshop")] },
        { title: "Anatomi Ezber Teknikleri", description: "Tıp öğrencisiyim, anatomi terimlerini akılda tutmak için kullandığım yöntemleri paylaşıyorum. Görsel ve hikayeleştirme teknikleriyle ezber çok kolaylaşıyor. Sınav öncesi hızlı tekrar seansları yapıyorum.", price: 350, type: "course", location: "Balçova, İzmir", subject: "Tıp", format: "in_person", criteria: { "Konu": "Anatomi", "Yöntem": "Hafıza teknikleri", "Hedef": "Sınav" }, photos: [pic("ders-anatomi")] },
        { title: "Excel ile Veri Yönetimi", description: "İşletme ve mühendislik öğrencileri için Excel'i verimli kullanmayı öğretiyorum. Formüller, pivot tablolar ve grafikleri iş hayatına hazır seviyede geçiyoruz. Örnek dosyalarla pratik yapıyoruz.", price: 280, type: "course", location: "Online", subject: "Ofis Programları", format: "online", criteria: { "Program": "Excel", "Konu": "Pivot + formül", "Materyal": "Örnek dosya" }, photos: [pic("ders-excel")] },
        { title: "Diferansiyel Denklemler", description: "Bu ders çoğu mühendisin kabusu ama doğru anlatılınca çok mantıklı. Çözüm tiplerini sınıflandırıp her birine örnek veriyorum. Ödevlerinde de takıldığın yerde destek olurum.", price: 300, type: "course", location: "Buca, İzmir", subject: "Matematik", format: "in_person", criteria: { "Konu": "Dif. denklemler", "Destek": "Ödev dahil", "Yer": "Kampüs/kafe" }, photos: [pic("ders-difdenk")] },
        { title: "Fransızca Sohbet Kulübü", description: "Fransızcasını ilerletmek isteyen orta seviye öğrencilerle küçük gruplar halinde konuşuyoruz. Film ve şarkılardan da yararlanıyoruz, keyifli bir ortam. Gramer hatalarını nazikçe düzeltiyorum.", price: 180, type: "course", location: "Online", subject: "Fransızca", format: "online", criteria: { "Seviye": "Orta", "Format": "Grup sohbeti", "Materyal": "Film + şarkı" }, photos: [pic("ders-fransizca")] },

        // ══════════════ NOTE (15) ══════════════
        { title: "Veri Yapıları ve Algoritmalar Notu", description: "Dönem boyunca titizlikle tuttuğum, tüm veri yapılarını örnek kodlarla anlatan notlar. Ağaçlar ve grafik algoritmaları özellikle detaylı. PDF olarak paylaşıyorum, çıktı almak isteyen alabilir.", price: 60, type: "note", location: "Bornova, İzmir", lecture: "Veri Yapıları", features: { "Format": "PDF", "Sayfa": "45 sayfa", "İçerik": "Kod örnekli" }, photos: [pic("not-veriyapilari")] },
        { title: "Mikroişlemciler Ders Notu", description: "Assembly ve mikroişlemci mimarisi konularını sadeleştiren notlarım. Hocanın sınavda çıkardığı tarz soruları da ekledim. El yazısı ama gayet düzenli ve okunaklı.", price: 50, type: "note", location: "Buca, İzmir", lecture: "Mikroişlemciler", features: { "Tip": "El yazısı", "Ek": "Örnek sınav soruları" }, photos: [pic("not-mikroislemci")] },
        { title: "Genel Muhasebe Özet Notları", description: "İşletme birinci sınıf muhasebe dersinin tüm yevmiye kayıtlarını örneklerle topladım. Dönem sonu işlemleri adım adım anlatılıyor. Final öncesi göz gezdirmek için birebir.", price: 40, type: "note", location: "Konak, İzmir", lecture: "Genel Muhasebe", features: { "İçerik": "Yevmiye örnekleri", "Format": "Özet" }, photos: [pic("not-muhasebe")] },
        { title: "Termodinamik Formül Kağıdı", description: "Bütün termodinamik formüllerini tek bir organize sayfada topladım, sınavda çok işe yarıyor. Hangi formülü ne zaman kullanacağını da not düştüm. Laminasyonlu haliyle veriyorum.", price: 30, type: "note", location: "Bornova, İzmir", lecture: "Termodinamik", features: { "Tip": "Formül özeti", "Ek": "Kullanım notları" }, photos: [pic("not-termodinamik")] },
        { title: "Anayasa Hukuku Ders Notu", description: "Hukuk fakültesi anayasa dersinin kapsamlı notları, güncel değişiklikler dahil. Önemli maddeler renkli işaretli. Vize ve final ayrımı yaparak düzenledim.", price: 55, type: "note", location: "Alsancak, İzmir", lecture: "Anayasa Hukuku", features: { "İçerik": "Güncel maddeler", "Düzen": "Vize/final ayrımı" }, photos: [pic("not-anayasa")] },
        { title: "Fizyoloji Konu Anlatım Notu", description: "Tıp fizyoloji derslerinin şema ağırlıklı notları, karmaşık sistemler görsellerle basitleştirildi. Sınıf notlarımı temize çektim. Kalp ve sinir sistemi bölümleri özellikle detaylı.", price: 70, type: "note", location: "Balçova, İzmir", lecture: "Fizyoloji", features: { "Tip": "Şemalı", "Detay": "Kalp + sinir sistemi" }, photos: [pic("not-fizyoloji")] },
        { title: "Olasılık Teorisi Çözümlü Notlar", description: "Olasılık dersinin tüm konularını çözümlü örneklerle anlattığım notlar. Her konudan sonra alıştırma soruları var. Kendi başına çalışan biri için yeterli bir kaynak.", price: 45, type: "note", location: "Bornova, İzmir", lecture: "Olasılık", features: { "İçerik": "Çözümlü örnek", "Ek": "Alıştırma" }, photos: [pic("not-olasilik")] },
        { title: "Pazarlama İlkeleri Özeti", description: "İşletme pazarlama dersinin tüm kavramlarını akılda kalıcı şekilde özetledim. Vakalar ve örnek markalarla desteklenmiş. Sınav gecesi hızlı tekrar için ideal uzunlukta.", price: 35, type: "note", location: "Karşıyaka, İzmir", lecture: "Pazarlama İlkeleri", features: { "Format": "Özet", "İçerik": "Vaka örnekli" }, photos: [pic("not-pazarlama")] },
        { title: "Statik Ders Çözümlü Problemler", description: "İnşaat ve makine mühendisliği statik dersinin çözümlü problem arşivi. Kuvvet ve moment hesaplarını adım adım gösterdim. Ödevlerde çok işine yarar.", price: 50, type: "note", location: "Buca, İzmir", lecture: "Statik", features: { "Tip": "Çözümlü problem", "Konu": "Kuvvet + moment" }, photos: [pic("not-statik")] },
        { title: "İşletim Sistemleri Kavram Notu", description: "Süreç yönetimi, bellek ve dosya sistemleri konularını sadeleştiren notlar. Bol diyagramlı, karmaşık konular görselleşince oturuyor. Bilgisayar bölümü için birebir.", price: 55, type: "note", location: "Bornova, İzmir", lecture: "İşletim Sistemleri", features: { "İçerik": "Diyagramlı", "Konu": "Süreç + bellek" }, photos: [pic("not-isletim")] },
        { title: "Genel Kimya Laboratuvar Raporları", description: "Dönem boyunca hazırladığım tüm lab raporlarının derli toplu hali. Deney düzeneği çizimleri ve hesaplamalar tam. Rapor formatına örnek arayanlar için de faydalı.", price: 40, type: "note", location: "Konak, İzmir", lecture: "Genel Kimya Lab", features: { "İçerik": "Deney raporları", "Ek": "Düzenek çizimleri" }, photos: [pic("not-kimyalab")] },
        { title: "Mikro İktisat Grafik Notları", description: "Arz-talep, esneklik ve piyasa dengesi gibi konuları grafikler üzerinden anlattım. Sınavlarda grafik yorumlama sorularına birebir hazırlık. Kavramlar sade dille açıklandı.", price: 45, type: "note", location: "Alsancak, İzmir", lecture: "Mikro İktisat", features: { "Tip": "Grafik ağırlıklı", "Konu": "Arz-talep" }, photos: [pic("not-mikroikt")] },
        { title: "Sinyaller ve Sistemler Notu", description: "Fourier ve Laplace dönüşümlerini örneklerle anlattığım kapsamlı notlar. Konuların birbirine bağlantısını gösteren bir akış hazırladım. Bu ders için en çok emek verdiğim not budur.", price: 60, type: "note", location: "Bornova, İzmir", lecture: "Sinyaller ve Sistemler", features: { "Konu": "Fourier + Laplace", "İçerik": "Örnekli" }, photos: [pic("not-sinyaller")] },
        { title: "Ceza Hukuku Genel Hükümler", description: "Hukuk fakültesi ceza dersinin genel hükümler kısmının detaylı notları. Suç unsurları şemalarla anlatıldı. Örnek olaylarla pekiştirilmiş, sınava yönelik hazırlandı.", price: 50, type: "note", location: "Konak, İzmir", lecture: "Ceza Hukuku", features: { "Konu": "Genel hükümler", "Ek": "Örnek olay" }, photos: [pic("not-ceza")] },
        { title: "Biyokimya Metabolizma Notu", description: "Metabolik yolakları renkli diyagramlarla özetlediğim notlar, ezberi çok kolaylaştırıyor. Glikoliz ve Krebs döngüsü adım adım. Tıp ve eczacılık öğrencileri için hazırlandı.", price: 65, type: "note", location: "Balçova, İzmir", lecture: "Biyokimya", features: { "Tip": "Renkli diyagram", "Konu": "Metabolizma" }, photos: [pic("not-biyokimya")] },

        // ══════════════ JOB (10) ══════════════
        { title: "Part-Time Kafe Barista", description: "Alsancak'taki üçüncü nesil kahve dükkanımız için hafta içi öğleden sonra çalışacak barista arıyoruz. Kahve tutkusu olan, güler yüzlü öğrenciler önceliğimiz. Deneyim şart değil, eğitim veriyoruz.", price: 0, type: "job", location: "Alsancak, İzmir", application_url: "https://kariyer.example.com/ilan/barista-alsancak", deadline: inDays(15), features: { "Çalışma": "Part-time", "Vardiya": "Öğleden sonra", "Deneyim": "Şart değil" }, photos: [pic("is-barista")] },
        { title: "Web Geliştirme Stajyeri", description: "Bornova'daki yazılım startup'ımızda React öğrenmek isteyen stajyer arıyoruz. Gerçek projelerde mentor eşliğinde çalışacaksınız. Esnek saatler, öğrenci dostu bir ortam sunuyoruz.", price: 0, type: "job", location: "Bornova, İzmir", application_url: "https://kariyer.example.com/ilan/frontend-stajyer", deadline: inDays(20), features: { "Pozisyon": "Stajyer", "Teknoloji": "React", "Saat": "Esnek" }, photos: [pic("is-webdev")] },
        { title: "Matematik Özel Ders Öğretmeni", description: "Lise öğrencilerine matematik dersi verecek üniversite öğrencisi arıyoruz. Eğitim gönüllüsü, sabırlı adaylar tercih edilir. Ders başı ücret oldukça tatmin edici.", price: 350, type: "job", location: "Karşıyaka, İzmir", application_url: "https://kariyer.example.com/ilan/matematik-ogretmen", deadline: inDays(10), features: { "Alan": "Matematik", "Hedef kitle": "Lise", "Ücret": "Ders başı" }, photos: [pic("is-ozelders")] },
        { title: "Sosyal Medya İçerik Editörü", description: "Yerel bir markanın Instagram ve TikTok hesaplarını yönetecek yaratıcı bir öğrenci arıyoruz. Video kurgu ve tasarım bilgisi artı puan. Uzaktan çalışma imkanı var.", price: 0, type: "job", location: "Uzaktan", application_url: "https://kariyer.example.com/ilan/sosyal-medya", deadline: inDays(18), features: { "Çalışma": "Uzaktan", "Beceri": "Kurgu + tasarım", "Platform": "Instagram/TikTok" }, photos: [pic("is-sosyalmedya")] },
        { title: "Etkinlik Görevlisi (Hafta Sonu)", description: "Fuar ve konser organizasyonlarımızda hafta sonu çalışacak enerjik ekip üyeleri arıyoruz. İletişimi güçlü, sorumluluk alabilen öğrenciler ideal. Günlük ödeme yapılıyor.", price: 0, type: "job", location: "Gaziemir, İzmir", application_url: "https://kariyer.example.com/ilan/etkinlik-gorevli", deadline: inDays(7), features: { "Zaman": "Hafta sonu", "Ödeme": "Günlük", "Nitelik": "İletişim güçlü" }, photos: [pic("is-etkinlik")] },
        { title: "Grafik Tasarım Freelance", description: "Küçük işletmeler için logo ve afiş tasarlayacak yetenekli bir tasarımcı arıyoruz. Portfolyonuzu başvuruda paylaşmanız yeterli. Proje bazlı, esnek çalışma modeli.", price: 0, type: "job", location: "Uzaktan", application_url: "https://kariyer.example.com/ilan/grafik-freelance", deadline: inDays(25), features: { "Model": "Proje bazlı", "Gereklilik": "Portfolyo", "Alan": "Logo + afiş" }, photos: [pic("is-grafik")] },
        { title: "Çağrı Merkezi Öğrenci Kadrosu", description: "Konak'taki ofisimizde vardiyalı çalışacak öğrenci ekip üyeleri alıyoruz. Ders programınıza uygun vardiya seçebilirsiniz. Diksiyonu düzgün, sabırlı adaylar aranıyor.", price: 0, type: "job", location: "Konak, İzmir", application_url: "https://kariyer.example.com/ilan/cagri-merkezi", deadline: inDays(12), features: { "Vardiya": "Esnek", "Nitelik": "Diksiyon", "Kadro": "Öğrenci" }, photos: [pic("is-cagrimerkezi")] },
        { title: "Veri Girişi (Uzaktan Part-Time)", description: "Evden yapılabilen, esnek saatli veri girişi işi için dikkatli öğrenciler arıyoruz. Temel Excel bilgisi yeterli. Haftalık iş yükü kendi programınıza göre ayarlanabilir.", price: 0, type: "job", location: "Uzaktan", application_url: "https://kariyer.example.com/ilan/veri-girisi", deadline: inDays(14), features: { "Çalışma": "Uzaktan", "Beceri": "Temel Excel", "Saat": "Esnek" }, photos: [pic("is-verigiris")] },
        { title: "Kütüphane Asistanı", description: "Kampüs kütüphanemizde raf düzeni ve öğrenci yönlendirmesinde çalışacak asistan alıyoruz. Sessiz ortamı sevenler için ideal, ders aralarında çalışabilirsiniz. Burslu öğrencilere öncelik.", price: 0, type: "job", location: "Kampüs", application_url: "https://kariyer.example.com/ilan/kutuphane-asistan", deadline: inDays(9), features: { "Yer": "Kampüs", "Ortam": "Sessiz", "Öncelik": "Burslu öğrenci" }, photos: [pic("is-kutuphane")] },
        { title: "Mağaza Satış Danışmanı", description: "Karşıyaka'daki giyim mağazamıza hafta sonu ve akşam vardiyalarında satış danışmanı arıyoruz. Moda ilgisi ve güler yüz en önemli kriterimiz. Prim sistemiyle kazanç artırılabilir.", price: 0, type: "job", location: "Karşıyaka, İzmir", application_url: "https://kariyer.example.com/ilan/satis-danisman", deadline: inDays(11), features: { "Vardiya": "Akşam/hafta sonu", "Kazanç": "Prim var", "Sektör": "Giyim" }, photos: [pic("is-satis")] },

        // ══════════════ SCHOLARSHIP (10) ══════════════
        { title: "Mühendislik Başarı Bursu", description: "Mühendislik fakültesi öğrencilerine yönelik, not ortalaması yüksek adaylara verilen aylık burs programı. Başvuruda transkript ve niyet mektubu isteniyor. Kontenjan sınırlı, erken başvuru öneriyoruz.", price: 0, type: "scholarship", location: "İzmir", amount: 3500, application_url: "https://burs.example.com/muhendislik-basari", deadline: inDays(30), features: { "Kapsam": "Mühendislik", "Kriter": "GPA yüksek", "Belge": "Transkript + mektup" }, photos: [pic("burs-muhendislik")] },
        { title: "Kız Öğrenci Destek Bursu", description: "STEM alanlarında okuyan kız öğrencileri desteklemek için oluşturulan burs fonu. Mentorluk programı da burs kapsamında sunuluyor. Bölge önceliği İzmir ve çevresi.", price: 0, type: "scholarship", location: "İzmir", amount: 4000, application_url: "https://burs.example.com/kiz-ogrenci-stem", deadline: inDays(28), features: { "Alan": "STEM", "Ek": "Mentorluk", "Bölge": "İzmir" }, photos: [pic("burs-kizogrenci")] },
        { title: "İhtiyaç Bursu (Tam Zamanlı)", description: "Maddi imkanı kısıtlı, çalışkan öğrenciler için tam zamanlı destek bursu. Aile gelir belgesi başvuruda değerlendiriliyor. Barınma desteği de talep edilebiliyor.", price: 0, type: "scholarship", location: "İzmir", amount: 5000, application_url: "https://burs.example.com/ihtiyac-bursu", deadline: inDays(21), features: { "Tür": "İhtiyaç bazlı", "Belge": "Gelir belgesi", "Ek": "Barınma desteği" }, photos: [pic("burs-ihtiyac")] },
        { title: "Sanat ve Tasarım Bursu", description: "Güzel sanatlar ve tasarım öğrencilerine portfolyo değerlendirmesiyle verilen burs. Sergileme ve atölye imkanları da sağlanıyor. Yaratıcı projeler öncelikli değerlendiriliyor.", price: 0, type: "scholarship", location: "İzmir", amount: 3000, application_url: "https://burs.example.com/sanat-tasarim", deadline: inDays(26), features: { "Alan": "Sanat/tasarım", "Değerlendirme": "Portfolyo", "Ek": "Atölye erişimi" }, photos: [pic("burs-sanat")] },
        { title: "Girişimcilik Fonu", description: "İş fikri olan öğrenci girişimcilere sermaye ve danışmanlık sağlayan program. İş planınızı sunmanız gerekiyor. Kazananlara ofis alanı da tahsis ediliyor.", price: 0, type: "scholarship", location: "İzmir", amount: 15000, application_url: "https://burs.example.com/girisimcilik-fonu", deadline: inDays(35), features: { "Tür": "Sermaye desteği", "Gereklilik": "İş planı", "Ek": "Ofis + danışmanlık" }, photos: [pic("burs-girisimcilik")] },
        { title: "Spor Başarı Bursu", description: "Üniversiteler arası müsabakalarda derece yapan sporcu öğrencilere yönelik burs. Antrenman ve ekipman desteği de kapsam içinde. Federasyon belgesi başvuruya eklenmeli.", price: 0, type: "scholarship", location: "İzmir", amount: 3200, application_url: "https://burs.example.com/spor-basari", deadline: inDays(24), features: { "Alan": "Spor", "Kriter": "Derece", "Ek": "Ekipman desteği" }, photos: [pic("burs-spor")] },
        { title: "Yüksek Lisans Araştırma Bursu", description: "Tez aşamasındaki yüksek lisans öğrencilerine araştırma projelerini desteklemek için verilen burs. Danışman onaylı proje önerisi isteniyor. Yayın çıkaranlara ek ödül sağlanıyor.", price: 0, type: "scholarship", location: "İzmir", amount: 6000, application_url: "https://burs.example.com/yl-arastirma", deadline: inDays(32), features: { "Seviye": "Yüksek lisans", "Gereklilik": "Proje önerisi", "Ek": "Yayın ödülü" }, photos: [pic("burs-arastirma")] },
        { title: "Dijital Beceriler Bursu", description: "Yazılım, veri bilimi ve dijital pazarlama öğrenmek isteyenlere kurs ücreti desteği. Sertifika programlarına erişim sağlanıyor. Sektör mentorlarıyla eşleştirme yapılıyor.", price: 0, type: "scholarship", location: "İzmir", amount: 2500, application_url: "https://burs.example.com/dijital-beceriler", deadline: inDays(27), features: { "Alan": "Dijital beceri", "Kapsam": "Kurs + sertifika", "Ek": "Mentor eşleşme" }, photos: [pic("burs-dijital")] },
        { title: "Erasmus Hareketlilik Desteği", description: "Yurt dışı değişim programına katılacak öğrencilere ek maddi destek fonu. Kabul mektubu ve dil belgesi başvuruda gerekiyor. Konaklama ve yol için kullanılabiliyor.", price: 0, type: "scholarship", location: "İzmir", amount: 8000, application_url: "https://burs.example.com/erasmus-destek", deadline: inDays(29), features: { "Program": "Erasmus", "Belge": "Kabul + dil belgesi", "Kullanım": "Konaklama/yol" }, photos: [pic("burs-erasmus")] },
        { title: "Sosyal Sorumluluk Bursu", description: "Gönüllülük ve toplumsal projelerde aktif rol alan öğrencilere verilen teşvik bursu. Yürüttüğün projeyi anlatan bir dosya sunman yeterli. Topluma katkı önceliğimizdir.", price: 0, type: "scholarship", location: "İzmir", amount: 2800, application_url: "https://burs.example.com/sosyal-sorumluluk", deadline: inDays(23), features: { "Kriter": "Gönüllülük", "Gereklilik": "Proje dosyası", "Odak": "Topluma katkı" }, photos: [pic("burs-sosyal")] },

        // ══════════════ URGENT (5) ══════════════
        { title: "ACİL: Bugün Ders Kitabı Lazım", description: "Yarın sabah vize var ve İktisada Giriş kitabına acilen ihtiyacım var. Elinde olan varsa bugün buluşup alabilirim, para bekletmem. Bornova çevresinde olması harika olur.", price: 150, type: "urgent", location: "Bornova, İzmir", features: { "Aciliyet": "Bugün", "İhtiyaç": "İktisada Giriş kitabı" }, photos: [pic("acil-kitap")], expires: inHours(8) },
        { title: "ACİL: Yarın İçin Takım Elbise", description: "Yarın mezuniyet töreni var ve takım elbisem hazır değil, 48 beden acil arıyorum. Kiralık ya da satılık fark etmez, bugün akşama kadar lazım. Alsancak'ta buluşabilirim.", price: 500, type: "urgent", location: "Alsancak, İzmir", features: { "Aciliyet": "Yarın töreni", "Beden": "48", "Seçenek": "Kiralık/satılık" }, photos: [pic("acil-takim")], expires: inHours(20) },
        { title: "ACİL: Taşınma İçin Koli ve İp", description: "Bu akşam evden çıkıyorum ve koli, balonlu naylon ve ip acil lazım. Kim varsa hemen alırım, birkaç saat içinde. Buca'da olan biri kurtarır beni.", price: 100, type: "urgent", location: "Buca, İzmir", features: { "Aciliyet": "Bu akşam", "İhtiyaç": "Koli + naylon + ip" }, photos: [pic("acil-koli")], expires: inHours(6) },
        { title: "ACİL: Hesap Makinesi (Sınav)", description: "İki saat sonra finalim var ve bilimsel hesap makinemi evde unutmuşum. Kampüste olan biri ödünç verebilir mi, sınav bitince hemen iade ederim. Kampüs içinde buluşalım lütfen.", price: 0, type: "urgent", location: "Kampüs", features: { "Aciliyet": "2 saat sonra", "Tip": "Ödünç", "İhtiyaç": "Bilimsel hesap makinesi" }, photos: [pic("acil-hesapmakinesi")], expires: inHours(3) },
        { title: "ACİL: Bu Gece Kalacak Yer", description: "Ev sözleşmem bugün bitti ve yeni ev pazartesi hazır, iki geceliğine kalacak yere ihtiyacım var. Kanepe bile olur, temiz ve sessiz biriyim. Karşıyaka çevresi ideal olur.", price: 300, type: "urgent", location: "Karşıyaka, İzmir", features: { "Aciliyet": "Bu gece", "Süre": "2 gece", "İhtiyaç": "Geçici konaklama" }, photos: [pic("acil-kalacakyer")], expires: inHours(10) },
    ];

    console.log("Seeding: creating listings...");
    let count = 0;
    for (const l of listings) {
        await prisma.listing.create({
            data: {
                ...l,
                ownerId: nextOwner(),
                status: "active",
                is_deleted: false,
                expires: l.expires ?? (l.type === "urgent" ? inHours(6) : oneMonthLater()),
            } as any,
        });
        count++;
    }
    console.log(`Created ${count} listings.`);
    console.log("Seed complete.");
}

main()
    .catch((e) => {
        console.error("Seed failed:", e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });